/**
 * Hardmaxxing Surgery Database
 * Comprehensive database of facial aesthetic surgeries
 */

import { Surgery, RegionalCost } from './types';

export const SURGICAL_TREATMENTS: Surgery[] = [
  // ============================================
  // RHINOPLASTY (NOSE SURGERIES)
  // ============================================
  {
    id: 'rhinoplasty_reduction',
    name: 'Reduction Rhinoplasty',
    category: 'surgical',
    description: 'Surgical reduction of nose size, hump removal, and tip refinement',
    howItWorks: 'Surgeon removes bone and cartilage to reduce overall nose size, refine the tip, and straighten the bridge',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.5, max: 1.0 },
    costLevel: 'very_high',
    costRange: { min: 5000, max: 15000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: 'Initial results at 2-4 weeks, final results at 12-18 months',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '1-2 weeks for major swelling, full recovery 12-18 months',
    downtime: '1-2 weeks off work',
    painLevel: 'moderate',
    riskLevel: 'medium',
    sideEffects: ['Swelling', 'Bruising', 'Numbness', 'Breathing changes', 'Asymmetry'],
    contraindications: ['Unrealistic expectations', 'Active skin infections', 'Bleeding disorders'],
    targetMetrics: ['nasal_index', 'nasolabial_angle', 'nasofrontal_angle', 'overall_harmony'],
    targetIssues: ['large_nose', 'dorsal_hump', 'bulbous_tip', 'wide_nose', 'crooked_nose'],
    permanence: 'permanent',
    anesthesiaType: 'general',
    revisionRate: 0.15,
    regionalCosts: [
      { region: 'USA', min: 7000, max: 15000, currency: 'USD' },
      { region: 'Turkey', min: 2500, max: 5000, currency: 'USD', notes: 'Popular medical tourism destination' },
      { region: 'South Korea', min: 4000, max: 10000, currency: 'USD', notes: 'K-beauty rhinoplasty style' },
      { region: 'Mexico', min: 3000, max: 6000, currency: 'USD', notes: 'Tijuana/Guadalajara - board certified surgeons' },
      { region: 'UK', min: 5000, max: 12000, currency: 'GBP', notes: 'Harley Street specialists' },
      { region: 'Germany', min: 5500, max: 13000, currency: 'EUR', notes: 'Munich/Berlin - high standards' },
      { region: 'Spain', min: 4000, max: 9000, currency: 'EUR', notes: 'Barcelona/Madrid - growing medical tourism' },
      { region: 'Thailand', min: 2500, max: 5500, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 3000, max: 6000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    surgeonRecommendations: [
      { name: 'Dr. Sam Rizk', location: 'New York, USA', specialty: 'Preservation rhinoplasty', costRange: '$15,000-25,000' },
      { name: 'Dr. Paul Nassif', location: 'Beverly Hills, USA', specialty: 'Revision rhinoplasty', costRange: '$12,000-30,000' },
      { name: 'Dr. Amir Keshavarz', location: 'Istanbul, Turkey', specialty: 'Ethnic rhinoplasty', costRange: '$3,000-6,000' },
    ],
    notes: [
      '85% satisfaction rate on RealSelf',
      'Most requested cosmetic surgery worldwide',
      'Preservation rhinoplasty has faster recovery but limited to certain nose types',
      'Ethnic rhinoplasty maintains cultural features while enhancing proportions',
    ],
    sources: ['ASPS', 'RealSelf', 'JAMA Facial Plastic Surgery'],
  },
  {
    id: 'rhinoplasty_tip',
    name: 'Tip Rhinoplasty (Tipplasty)',
    category: 'surgical',
    description: 'Focused nasal tip refinement without bridge modification',
    howItWorks: 'Reshapes tip cartilages through closed or open approach, refining tip projection and rotation',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.3, max: 0.7 },
    costLevel: 'high',
    costRange: { min: 3500, max: 8000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '2-4 weeks initial, 6-12 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '1 week for major swelling',
    downtime: '5-7 days off work',
    painLevel: 'low',
    riskLevel: 'low',
    sideEffects: ['Tip swelling', 'Minor bruising', 'Temporary numbness'],
    contraindications: ['Bridge concerns', 'Severe tip deformities'],
    targetMetrics: ['nasolabial_angle', 'tip_projection', 'overall_harmony'],
    targetIssues: ['bulbous_tip', 'droopy_tip', 'upturned_tip', 'tip_asymmetry'],
    permanence: 'permanent',
    anesthesiaType: 'local',
    revisionRate: 0.10,
    regionalCosts: [
      { region: 'USA', min: 4000, max: 8000, currency: 'USD' },
      { region: 'Turkey', min: 1500, max: 3000, currency: 'USD' },
      { region: 'South Korea', min: 2500, max: 5000, currency: 'USD' },
      { region: 'Mexico', min: 1800, max: 3500, currency: 'USD', notes: 'Tijuana/Guadalajara' },
      { region: 'UK', min: 3000, max: 6000, currency: 'GBP' },
      { region: 'Germany', min: 3200, max: 6500, currency: 'EUR' },
      { region: 'Spain', min: 2500, max: 5000, currency: 'EUR' },
      { region: 'Thailand', min: 1800, max: 3500, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 2000, max: 4000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    notes: [
      'Less invasive than full rhinoplasty',
      'Shorter recovery time',
      'Can be done under local anesthesia',
      'Ideal for patients with good bridge but tip concerns',
    ],
    sources: ['ASPS', 'RealSelf'],
  },
  {
    id: 'septorhinoplasty',
    name: 'Septorhinoplasty',
    category: 'surgical',
    description: 'Combination of septum repair and cosmetic rhinoplasty',
    howItWorks: 'Corrects deviated septum while reshaping external nose appearance',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.4, max: 0.9 },
    costLevel: 'very_high',
    costRange: { min: 6000, max: 18000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '2-4 weeks initial, 12-18 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '2 weeks for major swelling, full recovery 12-18 months',
    downtime: '1-2 weeks off work',
    painLevel: 'moderate',
    riskLevel: 'medium',
    sideEffects: ['Swelling', 'Bruising', 'Numbness', 'Septal perforation (rare)'],
    contraindications: ['Bleeding disorders', 'Active infections'],
    targetMetrics: ['nasal_index', 'nasolabial_angle', 'overall_harmony'],
    targetIssues: ['deviated_septum', 'breathing_issues', 'crooked_nose', 'asymmetry'],
    permanence: 'permanent',
    anesthesiaType: 'general',
    revisionRate: 0.12,
    regionalCosts: [
      { region: 'USA', min: 7000, max: 18000, currency: 'USD' },
      { region: 'Turkey', min: 3000, max: 6000, currency: 'USD' },
      { region: 'Mexico', min: 3500, max: 8000, currency: 'USD', notes: 'Tijuana/Mexico City' },
      { region: 'UK', min: 5500, max: 14000, currency: 'GBP' },
      { region: 'Germany', min: 6000, max: 15000, currency: 'EUR' },
      { region: 'Spain', min: 4500, max: 11000, currency: 'EUR' },
      { region: 'Thailand', min: 3000, max: 6500, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 3500, max: 7000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    notes: [
      'May be partially covered by insurance if septum is functionally deviated',
      'Combines functional and aesthetic improvement',
      'Two-for-one recovery period',
    ],
    sources: ['ASPS', 'AAO-HNS'],
  },

  // ============================================
  // JAW & CHIN SURGERIES
  // ============================================
  {
    id: 'genioplasty',
    name: 'Sliding Genioplasty',
    category: 'surgical',
    description: 'Chin advancement or setback by cutting and repositioning the chin bone',
    howItWorks: 'Horizontal osteotomy of the mandible allows the chin segment to be moved forward, backward, up, or down',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.5, max: 1.2 },
    costLevel: 'very_high',
    costRange: { min: 5000, max: 15000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '3-6 months for swelling resolution, 12 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '4-6 weeks',
    downtime: '1-2 weeks off work',
    painLevel: 'moderate',
    riskLevel: 'medium',
    sideEffects: ['Swelling', 'Numbness (temporary to permanent)', 'Asymmetry', 'Bone resorption'],
    contraindications: ['Active infections', 'Poor bone health', 'Unrealistic expectations'],
    targetMetrics: ['chin_projection', 'pogonion', 'facial_convexity', 'profile_harmony'],
    targetIssues: ['recessed_chin', 'weak_chin', 'chin_excess', 'facial_imbalance'],
    permanence: 'permanent',
    anesthesiaType: 'general',
    revisionRate: 0.08,
    regionalCosts: [
      { region: 'USA', min: 6000, max: 15000, currency: 'USD' },
      { region: 'South Korea', min: 4000, max: 8000, currency: 'USD' },
      { region: 'Turkey', min: 3000, max: 6000, currency: 'USD' },
      { region: 'Mexico', min: 3000, max: 7000, currency: 'USD', notes: 'Mexico City/Guadalajara' },
      { region: 'UK', min: 5000, max: 12000, currency: 'GBP' },
      { region: 'Germany', min: 5500, max: 13000, currency: 'EUR' },
      { region: 'Spain', min: 4000, max: 10000, currency: 'EUR' },
      { region: 'Thailand', min: 2500, max: 5000, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 3000, max: 6000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    surgeonRecommendations: [
      { name: 'Dr. Barry Eppley', location: 'Indianapolis, USA', specialty: 'Custom facial implants & genioplasty', costRange: '$8,000-15,000' },
      { name: 'Dr. Yaremchuk', location: 'Boston, USA', specialty: 'Facial skeletal surgery', costRange: '$10,000-20,000' },
    ],
    notes: [
      'More versatile than chin implants (can move in all directions)',
      'Uses your own bone - no implant rejection risk',
      '5-10% permanent numbness of lower lip',
      'Can be combined with jaw surgery for comprehensive lower third correction',
    ],
    sources: ['ASPS', 'AAOMS', 'PubMed'],
  },
  {
    id: 'chin_implant',
    name: 'Chin Implant (Mentoplasty)',
    category: 'surgical',
    description: 'Silicone or PEEK implant to augment chin projection',
    howItWorks: 'Implant placed through intraoral or submental incision, sits on the bone to increase projection',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.4, max: 0.9 },
    costLevel: 'high',
    costRange: { min: 3000, max: 8000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '2-4 weeks for swelling, 3 months final',
    resultsDuration: 'Permanent (may need replacement in 15-20 years)',
    maintenanceRequired: false,
    recoveryTime: '1-2 weeks',
    downtime: '3-7 days off work',
    painLevel: 'low',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Numbness', 'Implant shifting', 'Bone erosion', 'Infection'],
    contraindications: ['Active oral infections', 'Unrealistic expectations'],
    targetMetrics: ['chin_projection', 'profile_harmony'],
    targetIssues: ['recessed_chin', 'weak_chin', 'short_chin'],
    permanence: 'permanent',
    anesthesiaType: 'local',
    revisionRate: 0.05,
    regionalCosts: [
      { region: 'USA', min: 3500, max: 8000, currency: 'USD' },
      { region: 'Turkey', min: 2000, max: 4000, currency: 'USD' },
      { region: 'Mexico', min: 2000, max: 4500, currency: 'USD', notes: 'Tijuana/Monterrey' },
      { region: 'UK', min: 3000, max: 6500, currency: 'GBP' },
      { region: 'Germany', min: 3200, max: 7000, currency: 'EUR' },
      { region: 'Spain', min: 2500, max: 5500, currency: 'EUR' },
      { region: 'Thailand', min: 1500, max: 3000, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 2000, max: 4000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    notes: [
      'Faster recovery than genioplasty',
      'Reversible if desired',
      'Can only add projection, not reduce or move vertically',
      'Bone erosion occurs in many patients but rarely clinically significant',
      'PEEK implants more expensive but no erosion',
    ],
    sources: ['ASPS', 'RealSelf'],
  },
  {
    id: 'jaw_implants',
    name: 'Jaw Angle Implants',
    category: 'surgical',
    description: 'Implants to widen and define the jaw angles (gonion)',
    howItWorks: 'Silicone or PEEK implants placed over the mandibular angle to increase width and definition',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.5, max: 1.2 },
    costLevel: 'very_high',
    costRange: { min: 7000, max: 20000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '4-8 weeks for swelling, 3-6 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '2-4 weeks',
    downtime: '1-2 weeks off work',
    painLevel: 'moderate',
    riskLevel: 'medium',
    sideEffects: ['Swelling', 'Numbness', 'Asymmetry', 'Implant shifting', 'Masseter tightness'],
    contraindications: ['Active infections', 'Very thin soft tissue'],
    targetMetrics: ['gonial_angle', 'bigonial_width', 'jaw_width_ratio', 'fwhr'],
    targetIssues: ['narrow_jaw', 'weak_gonial_angle', 'round_face', 'undefined_jawline'],
    genderSpecific: 'male',
    permanence: 'permanent',
    anesthesiaType: 'general',
    revisionRate: 0.10,
    regionalCosts: [
      { region: 'USA', min: 8000, max: 20000, currency: 'USD' },
      { region: 'South Korea', min: 6000, max: 12000, currency: 'USD' },
      { region: 'Turkey', min: 4000, max: 8000, currency: 'USD' },
      { region: 'Mexico', min: 4000, max: 10000, currency: 'USD', notes: 'Mexico City - limited availability' },
      { region: 'UK', min: 7000, max: 16000, currency: 'GBP' },
      { region: 'Germany', min: 7500, max: 18000, currency: 'EUR' },
      { region: 'Spain', min: 5500, max: 14000, currency: 'EUR' },
      { region: 'Thailand', min: 4000, max: 9000, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 5000, max: 10000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    surgeonRecommendations: [
      { name: 'Dr. Barry Eppley', location: 'Indianapolis, USA', specialty: 'Custom wrap-around jaw implants', costRange: '$15,000-25,000' },
      { name: 'Dr. Yaremchuk', location: 'Boston, USA', specialty: 'Facial implants', costRange: '$12,000-20,000' },
    ],
    notes: [
      'Custom implants provide better results than stock',
      'Often combined with chin implant for comprehensive jawline',
      'Wrap-around implants cover jaw angle + body + chin',
      'PEEK implants cost more but no bone erosion',
    ],
    sources: ['ASPS', 'RealSelf', 'Dr. Eppley publications'],
  },
  {
    id: 'bsso',
    name: 'BSSO (Bilateral Sagittal Split Osteotomy)',
    category: 'surgical',
    description: 'Mandibular advancement or setback surgery for jaw positioning',
    howItWorks: 'The mandible is split and repositioned forward or backward, then fixed with titanium plates',
    effectiveness: 10,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.8, max: 2.0 },
    costLevel: 'very_high',
    costRange: { min: 20000, max: 50000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '3-6 months for major swelling, 12-18 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '6-8 weeks liquid/soft diet',
    downtime: '2-4 weeks off work',
    painLevel: 'high',
    riskLevel: 'high',
    sideEffects: ['Numbness (permanent in 10-15%)', 'Swelling', 'Relapse', 'TMJ issues', 'Malocclusion'],
    contraindications: ['Poor dental health', 'Bleeding disorders', 'Uncontrolled diabetes'],
    targetMetrics: ['chin_projection', 'gonial_angle', 'profile_harmony', 'facial_convexity'],
    targetIssues: ['recessed_mandible', 'prognathic_mandible', 'severe_overbite', 'severe_underbite'],
    permanence: 'permanent',
    anesthesiaType: 'general',
    hospitalStay: '1-2 nights',
    revisionRate: 0.05,
    regionalCosts: [
      { region: 'USA', min: 25000, max: 50000, currency: 'USD' },
      { region: 'South Korea', min: 15000, max: 25000, currency: 'USD' },
      { region: 'Mexico', min: 12000, max: 25000, currency: 'USD', notes: 'Mexico City - maxillofacial specialists' },
      { region: 'UK', min: 20000, max: 40000, currency: 'GBP' },
      { region: 'Germany', min: 20000, max: 40000, currency: 'EUR' },
      { region: 'Spain', min: 15000, max: 30000, currency: 'EUR' },
      { region: 'Thailand', min: 10000, max: 20000, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 12000, max: 25000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    notes: [
      'Usually requires 1-2 years of orthodontics before and after',
      'May be covered by insurance if medically necessary',
      'CCW rotation (counter-clockwise) is common in aesthetic cases',
      'Often combined with Le Fort I for bimax surgery',
    ],
    sources: ['AAOMS', 'Journal of Oral and Maxillofacial Surgery'],
  },
  {
    id: 'bimax',
    name: 'Bimaxillary Osteotomy (Bimax / Double Jaw Surgery)',
    category: 'surgical',
    description: 'Combined Le Fort I and BSSO to reposition both jaws',
    howItWorks: 'Upper jaw (maxilla) and lower jaw (mandible) are both cut and repositioned to optimal positions',
    effectiveness: 10,
    evidenceLevel: 'strong',
    pslImprovement: { min: 1.0, max: 2.5 },
    costLevel: 'very_high',
    costRange: { min: 30000, max: 80000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '6-12 months for major swelling, 18-24 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '6-8 weeks liquid/soft diet, 6-12 months full recovery',
    downtime: '4-6 weeks off work',
    painLevel: 'high',
    riskLevel: 'high',
    sideEffects: ['Numbness', 'Swelling', 'Relapse', 'TMJ issues', 'Nerve damage', 'Bleeding'],
    contraindications: ['Poor general health', 'Bleeding disorders', 'Uncontrolled diabetes', 'Smoking'],
    targetMetrics: ['facial_convexity', 'profile_harmony', 'midface_ratio', 'overall_harmony'],
    targetIssues: ['bimaxillary_protrusion', 'facial_asymmetry', 'long_face_syndrome', 'short_face_syndrome', 'severe_malocclusion'],
    permanence: 'permanent',
    anesthesiaType: 'general',
    hospitalStay: '2-3 nights',
    revisionRate: 0.08,
    regionalCosts: [
      { region: 'USA', min: 40000, max: 80000, currency: 'USD' },
      { region: 'South Korea', min: 20000, max: 35000, currency: 'USD', notes: 'Most popular destination for bimax' },
      { region: 'Mexico', min: 18000, max: 40000, currency: 'USD', notes: 'Mexico City - experienced surgeons' },
      { region: 'UK', min: 35000, max: 65000, currency: 'GBP', notes: 'NHS may cover functional cases' },
      { region: 'Germany', min: 30000, max: 50000, currency: 'EUR' },
      { region: 'Spain', min: 20000, max: 35000, currency: 'EUR', notes: 'Barcelona/Madrid - Dr. Alfaro recommended' },
      { region: 'Thailand', min: 15000, max: 30000, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 18000, max: 35000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    surgeonRecommendations: [
      { name: 'Dr. Alfaro', location: 'Barcelona, Spain', specialty: 'Aesthetic jaw surgery', costRange: '€25,000-35,000' },
      { name: 'Dr. Gunson/Arnett', location: 'Santa Barbara, USA', specialty: 'Orthognathic surgery', costRange: '$60,000-100,000' },
      { name: 'ID Hospital', location: 'Seoul, South Korea', specialty: 'V-line surgery', costRange: '$20,000-30,000' },
    ],
    notes: [
      'Most transformative facial surgery available',
      'Requires 12-24 months of orthodontics (braces)',
      'CCW rotation with maxillary advancement is the aesthetic gold standard',
      'May be partially covered by insurance if sleep apnea or functional issues',
      'Korea specializes in aesthetic bimax; Western surgeons often focus on function',
    ],
    sources: ['AAOMS', 'Dr. Arnett publications', 'Journal of Craniomaxillofacial Surgery'],
  },
  {
    id: 'mandible_reduction',
    name: 'Mandible Angle Reduction',
    category: 'surgical',
    description: 'Reduction of prominent jaw angles for a slimmer face shape',
    howItWorks: 'Bone is shaved or cut from the mandibular angle to reduce width and create V-line appearance',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.5, max: 1.0 },
    costLevel: 'very_high',
    costRange: { min: 8000, max: 25000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '3-6 months for swelling, 12 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '2-4 weeks',
    downtime: '1-2 weeks off work',
    painLevel: 'moderate',
    riskLevel: 'medium',
    sideEffects: ['Swelling', 'Numbness', 'Asymmetry', 'Masseter atrophy'],
    contraindications: ['Bleeding disorders', 'Active infections'],
    targetMetrics: ['bigonial_width', 'jaw_width_ratio', 'fwhr'],
    targetIssues: ['wide_jaw', 'square_jaw', 'masculine_jaw'],
    genderSpecific: 'female',
    permanence: 'permanent',
    anesthesiaType: 'general',
    revisionRate: 0.07,
    regionalCosts: [
      { region: 'South Korea', min: 8000, max: 15000, currency: 'USD', notes: 'V-line surgery capital' },
      { region: 'USA', min: 15000, max: 25000, currency: 'USD' },
      { region: 'Mexico', min: 7000, max: 14000, currency: 'USD', notes: 'Mexico City - limited specialists' },
      { region: 'UK', min: 12000, max: 20000, currency: 'GBP' },
      { region: 'Germany', min: 13000, max: 22000, currency: 'EUR' },
      { region: 'Spain', min: 10000, max: 18000, currency: 'EUR' },
      { region: 'Thailand', min: 6000, max: 12000, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 7000, max: 14000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    notes: [
      'Very popular in East Asia for V-line face shape',
      'Often combined with chin reduction for full V-line',
      'Can also be achieved with Botox for masseter (non-surgical)',
      'Long curve osteotomy provides most natural result',
    ],
    sources: ['Korean aesthetic surgery journals', 'ASPS'],
  },

  // ============================================
  // CHEEK & MIDFACE SURGERIES
  // ============================================
  {
    id: 'cheek_implants',
    name: 'Cheek Implants (Malar/Submalar)',
    category: 'surgical',
    description: 'Silicone or PEEK implants to augment cheekbone projection',
    howItWorks: 'Implants placed over the malar (cheekbone) or submalar area through intraoral incision',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.4, max: 1.0 },
    costLevel: 'high',
    costRange: { min: 4000, max: 12000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '4-8 weeks for swelling, 3-6 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '1-2 weeks',
    downtime: '1 week off work',
    painLevel: 'moderate',
    riskLevel: 'medium',
    sideEffects: ['Swelling', 'Numbness', 'Asymmetry', 'Implant shifting', 'Bone erosion'],
    contraindications: ['Very thin soft tissue', 'Active infections'],
    targetMetrics: ['cheekbone_projection', 'fwhr', 'midface_ratio', 'overall_harmony'],
    targetIssues: ['flat_cheeks', 'midface_deficiency', 'sunken_cheeks', 'aging_midface'],
    permanence: 'permanent',
    anesthesiaType: 'local',
    revisionRate: 0.08,
    regionalCosts: [
      { region: 'USA', min: 5000, max: 12000, currency: 'USD' },
      { region: 'Turkey', min: 3000, max: 6000, currency: 'USD' },
      { region: 'South Korea', min: 4000, max: 8000, currency: 'USD' },
      { region: 'Mexico', min: 2500, max: 6000, currency: 'USD', notes: 'Mexico City/Guadalajara' },
      { region: 'UK', min: 4000, max: 10000, currency: 'GBP' },
      { region: 'Germany', min: 4500, max: 11000, currency: 'EUR' },
      { region: 'Spain', min: 3500, max: 8000, currency: 'EUR' },
      { region: 'Thailand', min: 2500, max: 5000, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 3000, max: 6000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    notes: [
      'Malar implants: on cheekbone for projection',
      'Submalar implants: below cheekbone for fullness',
      'Combined malar-submalar for comprehensive midface enhancement',
      'Custom implants provide best results but cost more',
    ],
    sources: ['ASPS', 'RealSelf'],
  },
  {
    id: 'zygoma_reduction',
    name: 'Zygoma Reduction (Cheekbone Reduction)',
    category: 'surgical',
    description: 'Reduction of prominent cheekbones for narrower midface',
    howItWorks: 'Zygomatic arch is cut and repositioned inward to reduce facial width',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.4, max: 0.9 },
    costLevel: 'very_high',
    costRange: { min: 10000, max: 25000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '3-6 months for swelling, 12 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '2-4 weeks',
    downtime: '2 weeks off work',
    painLevel: 'moderate',
    riskLevel: 'medium',
    sideEffects: ['Swelling', 'Numbness', 'Asymmetry', 'Cheek sagging'],
    contraindications: ['Bleeding disorders', 'Active infections'],
    targetMetrics: ['bizygomatic_width', 'fwhr', 'facial_width'],
    targetIssues: ['wide_cheekbones', 'prominent_zygoma', 'wide_midface'],
    permanence: 'permanent',
    anesthesiaType: 'general',
    revisionRate: 0.06,
    regionalCosts: [
      { region: 'South Korea', min: 10000, max: 18000, currency: 'USD', notes: 'Most experienced surgeons globally' },
      { region: 'USA', min: 15000, max: 25000, currency: 'USD' },
      { region: 'Mexico', min: 8000, max: 15000, currency: 'USD', notes: 'Mexico City - limited availability' },
      { region: 'UK', min: 12000, max: 22000, currency: 'GBP' },
      { region: 'Germany', min: 13000, max: 23000, currency: 'EUR' },
      { region: 'Spain', min: 10000, max: 18000, currency: 'EUR' },
      { region: 'Thailand', min: 7000, max: 14000, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 8000, max: 16000, currency: 'USD', notes: 'Sao Paulo' },
    ],
    notes: [
      'Popular in East Asia where high cheekbones common',
      'Risk of cheek sagging if soft tissue not managed',
      'Often combined with V-line jaw reduction',
    ],
    sources: ['Korean aesthetic surgery journals'],
  },
  {
    id: 'lefort_1',
    name: 'Le Fort I Osteotomy (Maxillary Advancement)',
    category: 'surgical',
    description: 'Repositioning of the upper jaw (maxilla)',
    howItWorks: 'Maxilla is cut and moved forward, backward, up, or down, then fixed with titanium plates',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.6, max: 1.5 },
    costLevel: 'very_high',
    costRange: { min: 20000, max: 45000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '3-6 months for swelling, 12-18 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '4-6 weeks',
    downtime: '2-4 weeks off work',
    painLevel: 'moderate',
    riskLevel: 'medium',
    sideEffects: ['Swelling', 'Numbness', 'Relapse', 'Bleeding', 'Deviated septum'],
    contraindications: ['Poor dental health', 'Bleeding disorders'],
    targetMetrics: ['midface_projection', 'nasolabial_angle', 'upper_lip_support', 'facial_convexity'],
    targetIssues: ['recessed_maxilla', 'midface_deficiency', 'long_face', 'short_face', 'gummy_smile'],
    permanence: 'permanent',
    anesthesiaType: 'general',
    hospitalStay: '1-2 nights',
    revisionRate: 0.06,
    regionalCosts: [
      { region: 'USA', min: 25000, max: 45000, currency: 'USD' },
      { region: 'South Korea', min: 12000, max: 20000, currency: 'USD' },
      { region: 'Mexico', min: 12000, max: 22000, currency: 'USD', notes: 'Mexico City' },
      { region: 'UK', min: 18000, max: 35000, currency: 'GBP' },
      { region: 'Germany', min: 20000, max: 38000, currency: 'EUR' },
      { region: 'Spain', min: 15000, max: 25000, currency: 'EUR' },
      { region: 'Thailand', min: 10000, max: 18000, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 12000, max: 22000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    notes: [
      'Often combined with BSSO for bimax surgery',
      'Can correct gummy smile by impacting maxilla upward',
      'May improve nasal breathing',
      'Usually requires orthodontics before and after',
    ],
    sources: ['AAOMS', 'Journal of Oral and Maxillofacial Surgery'],
  },

  // ============================================
  // EYE SURGERIES
  // ============================================
  {
    id: 'canthoplasty',
    name: 'Canthoplasty (Lateral Canthopexy)',
    category: 'surgical',
    description: 'Surgical repositioning of the outer corner of the eye',
    howItWorks: 'Lateral canthal tendon is released and reattached at a higher position to lift eye corner',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.3, max: 0.7 },
    costLevel: 'high',
    costRange: { min: 4000, max: 12000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '2-4 weeks for swelling, 3-6 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '2-3 weeks',
    downtime: '1-2 weeks off work',
    painLevel: 'low',
    riskLevel: 'medium',
    sideEffects: ['Swelling', 'Bruising', 'Asymmetry', 'Dry eyes', 'Ectropion (eyelid turning out)'],
    contraindications: ['Dry eye syndrome', 'Previous eyelid surgery', 'Unrealistic expectations'],
    targetMetrics: ['canthal_tilt', 'palpebral_fissure', 'eye_area'],
    targetIssues: ['negative_canthal_tilt', 'droopy_eyes', 'sad_eyes', 'aging_eyes'],
    permanence: 'permanent',
    anesthesiaType: 'local',
    revisionRate: 0.12,
    regionalCosts: [
      { region: 'USA', min: 5000, max: 12000, currency: 'USD' },
      { region: 'South Korea', min: 3000, max: 6000, currency: 'USD' },
      { region: 'Turkey', min: 2500, max: 5000, currency: 'USD' },
      { region: 'Mexico', min: 2500, max: 5500, currency: 'USD', notes: 'Mexico City' },
      { region: 'UK', min: 4000, max: 10000, currency: 'GBP' },
      { region: 'Germany', min: 4500, max: 10000, currency: 'EUR' },
      { region: 'Spain', min: 3500, max: 8000, currency: 'EUR' },
      { region: 'Thailand', min: 2000, max: 4500, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 2500, max: 5500, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    surgeonRecommendations: [
      { name: 'Dr. Taban', location: 'Los Angeles, USA', specialty: 'Oculoplastic surgery', costRange: '$8,000-15,000' },
    ],
    notes: [
      'High satisfaction but also higher revision rate',
      'Fox eye look is a more aggressive version',
      'Conservative approach recommended to avoid unnatural look',
      'Thread canthoplasty is less invasive but temporary',
    ],
    sources: ['ASOPRS', 'RealSelf'],
  },
  {
    id: 'upper_blepharoplasty',
    name: 'Upper Blepharoplasty (Eyelid Surgery)',
    category: 'surgical',
    description: 'Removal of excess skin and fat from upper eyelids',
    howItWorks: 'Excess skin, muscle, and fat are removed through incision hidden in eyelid crease',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.2, max: 0.6 },
    costLevel: 'medium',
    costRange: { min: 2500, max: 7000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '2-4 weeks for swelling, 3 months final',
    resultsDuration: 'Long-lasting (10-15 years)',
    maintenanceRequired: false,
    recoveryTime: '1-2 weeks',
    downtime: '5-7 days off work',
    painLevel: 'low',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Bruising', 'Dry eyes', 'Asymmetry', 'Scarring'],
    contraindications: ['Dry eye syndrome', 'Glaucoma', 'Thyroid eye disease'],
    targetMetrics: ['upper_eyelid_exposure', 'palpebral_fissure', 'eye_area'],
    targetIssues: ['hooded_eyelids', 'excess_eyelid_skin', 'aging_eyes', 'tired_appearance'],
    permanence: 'semi-permanent',
    anesthesiaType: 'local',
    revisionRate: 0.05,
    regionalCosts: [
      { region: 'USA', min: 3000, max: 7000, currency: 'USD' },
      { region: 'Turkey', min: 1500, max: 3000, currency: 'USD' },
      { region: 'South Korea', min: 2000, max: 4000, currency: 'USD' },
      { region: 'Mexico', min: 1500, max: 3500, currency: 'USD', notes: 'Tijuana/Mexico City' },
      { region: 'UK', min: 2500, max: 5500, currency: 'GBP' },
      { region: 'Germany', min: 2800, max: 6000, currency: 'EUR' },
      { region: 'Spain', min: 2000, max: 4500, currency: 'EUR' },
      { region: 'Thailand', min: 1500, max: 3500, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 1800, max: 3500, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    notes: [
      'One of the most common facial surgeries',
      'May be covered by insurance if obstructing vision',
      'Hidden incision in natural crease',
      'Double eyelid surgery (Asian blepharoplasty) is different procedure',
    ],
    sources: ['ASPS', 'RealSelf'],
  },
  {
    id: 'lower_blepharoplasty',
    name: 'Lower Blepharoplasty',
    category: 'surgical',
    description: 'Treatment of under-eye bags and excess skin',
    howItWorks: 'Fat is repositioned or removed, and excess skin removed through incision below lash line or inside eyelid',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.2, max: 0.5 },
    costLevel: 'high',
    costRange: { min: 4000, max: 10000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '2-4 weeks for swelling, 3-6 months final',
    resultsDuration: 'Long-lasting (10-15 years)',
    maintenanceRequired: false,
    recoveryTime: '2 weeks',
    downtime: '7-10 days off work',
    painLevel: 'low',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Bruising', 'Dry eyes', 'Ectropion', 'Hollowing'],
    contraindications: ['Dry eye syndrome', 'Thyroid disorders'],
    targetMetrics: ['infraorbital_area', 'tear_trough', 'eye_area'],
    targetIssues: ['eye_bags', 'dark_circles', 'excess_lower_lid_skin', 'aging_eyes'],
    permanence: 'semi-permanent',
    anesthesiaType: 'local',
    revisionRate: 0.08,
    regionalCosts: [
      { region: 'USA', min: 5000, max: 10000, currency: 'USD' },
      { region: 'Turkey', min: 2000, max: 4000, currency: 'USD' },
      { region: 'South Korea', min: 2500, max: 5000, currency: 'USD' },
      { region: 'Mexico', min: 2500, max: 5000, currency: 'USD', notes: 'Tijuana/Mexico City' },
      { region: 'UK', min: 4000, max: 8000, currency: 'GBP' },
      { region: 'Germany', min: 4500, max: 9000, currency: 'EUR' },
      { region: 'Spain', min: 3500, max: 7000, currency: 'EUR' },
      { region: 'Thailand', min: 2000, max: 4000, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 2500, max: 4500, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    notes: [
      'Transconjunctival approach (inside eyelid) leaves no visible scar',
      'Fat repositioning preferred over removal to avoid hollow look',
      'Often combined with fat transfer for best results',
    ],
    sources: ['ASPS', 'RealSelf'],
  },
  {
    id: 'orbital_decompression',
    name: 'Orbital Rim Implants',
    category: 'surgical',
    description: 'Implants to augment the bony rim around the eye',
    howItWorks: 'Custom implants placed along infraorbital or supraorbital rim to improve eye support',
    effectiveness: 8,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.4, max: 0.8 },
    costLevel: 'very_high',
    costRange: { min: 10000, max: 25000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '4-8 weeks for swelling, 6 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '2-4 weeks',
    downtime: '1-2 weeks off work',
    painLevel: 'moderate',
    riskLevel: 'medium',
    sideEffects: ['Swelling', 'Numbness', 'Implant visibility', 'Asymmetry'],
    contraindications: ['Thyroid eye disease', 'Very thin skin'],
    targetMetrics: ['infraorbital_rim', 'upper_eyelid_support', 'eye_area'],
    targetIssues: ['negative_orbital_vector', 'under_eye_hollows', 'prominent_eyes', 'aging_midface'],
    permanence: 'permanent',
    anesthesiaType: 'general',
    revisionRate: 0.10,
    regionalCosts: [
      { region: 'USA', min: 12000, max: 25000, currency: 'USD' },
      { region: 'South Korea', min: 8000, max: 18000, currency: 'USD', notes: 'Seoul - custom implant specialists' },
      { region: 'Mexico', min: 6000, max: 14000, currency: 'USD', notes: 'Mexico City - limited availability' },
      { region: 'UK', min: 10000, max: 22000, currency: 'GBP' },
      { region: 'Germany', min: 11000, max: 23000, currency: 'EUR' },
      { region: 'Spain', min: 8000, max: 18000, currency: 'EUR' },
      { region: 'Thailand', min: 6000, max: 14000, currency: 'USD', notes: 'Bangkok - growing expertise' },
      { region: 'Brazil', min: 7000, max: 16000, currency: 'USD', notes: 'Sao Paulo' },
    ],
    surgeonRecommendations: [
      { name: 'Dr. Barry Eppley', location: 'Indianapolis, USA', specialty: 'Custom facial implants', costRange: '$15,000-25,000' },
    ],
    notes: [
      'Custom implants designed from CT scan',
      'Can dramatically change eye appearance',
      'Often combined with other facial implants',
    ],
    sources: ['Dr. Eppley publications'],
  },

  // ============================================
  // FOREHEAD & BROW SURGERIES
  // ============================================
  {
    id: 'brow_lift',
    name: 'Endoscopic Brow Lift',
    category: 'surgical',
    description: 'Lifting of the eyebrows through minimally invasive technique',
    howItWorks: 'Small incisions in hairline allow endoscopic repositioning of brow tissue',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.2, max: 0.5 },
    costLevel: 'high',
    costRange: { min: 5000, max: 12000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '2-4 weeks for swelling, 3-6 months final',
    resultsDuration: 'Long-lasting (7-10 years)',
    maintenanceRequired: false,
    recoveryTime: '1-2 weeks',
    downtime: '7-10 days off work',
    painLevel: 'moderate',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Numbness', 'Hair loss at incisions', 'Asymmetry'],
    contraindications: ['Very high hairline', 'Male pattern baldness'],
    targetMetrics: ['brow_position', 'upper_eyelid_exposure', 'eye_area'],
    targetIssues: ['low_brows', 'brow_ptosis', 'forehead_wrinkles', 'hooded_eyes_from_brow'],
    permanence: 'semi-permanent',
    anesthesiaType: 'sedation',
    revisionRate: 0.08,
    regionalCosts: [
      { region: 'USA', min: 6000, max: 12000, currency: 'USD' },
      { region: 'Turkey', min: 3000, max: 6000, currency: 'USD' },
      { region: 'Mexico', min: 3000, max: 6000, currency: 'USD', notes: 'Mexico City/Guadalajara' },
      { region: 'UK', min: 5000, max: 10000, currency: 'GBP' },
      { region: 'Germany', min: 5500, max: 11000, currency: 'EUR' },
      { region: 'Spain', min: 4000, max: 8000, currency: 'EUR' },
      { region: 'Thailand', min: 2000, max: 4000, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 2500, max: 5000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    notes: [
      'Less invasive than coronal brow lift',
      'Shorter recovery than traditional methods',
      'Can be combined with upper blepharoplasty',
      'Results last 7-10 years on average',
    ],
    sources: ['ASPS', 'RealSelf'],
  },
  {
    id: 'forehead_reduction',
    name: 'Forehead Reduction (Hairline Lowering)',
    category: 'surgical',
    description: 'Surgical lowering of the hairline by removing forehead skin',
    howItWorks: 'Scalp is advanced forward and excess forehead skin is removed',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.3, max: 0.7 },
    costLevel: 'high',
    costRange: { min: 7000, max: 15000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '4-8 weeks for swelling, 6-12 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '1-2 weeks',
    downtime: '7-10 days off work',
    painLevel: 'moderate',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Numbness', 'Visible scar', 'Hair shock loss'],
    contraindications: ['Male pattern baldness', 'Very tight scalp'],
    targetMetrics: ['facial_thirds', 'forehead_height', 'upper_third'],
    targetIssues: ['large_forehead', 'high_hairline', 'long_upper_third'],
    permanence: 'permanent',
    anesthesiaType: 'sedation',
    revisionRate: 0.05,
    regionalCosts: [
      { region: 'USA', min: 8000, max: 15000, currency: 'USD' },
      { region: 'Turkey', min: 4000, max: 8000, currency: 'USD' },
      { region: 'Mexico', min: 4000, max: 8000, currency: 'USD', notes: 'Mexico City' },
      { region: 'UK', min: 6500, max: 12000, currency: 'GBP' },
      { region: 'Germany', min: 7000, max: 13000, currency: 'EUR' },
      { region: 'Spain', min: 5500, max: 10000, currency: 'EUR' },
      { region: 'Thailand', min: 3500, max: 7000, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 4000, max: 8000, currency: 'USD', notes: 'Sao Paulo' },
    ],
    notes: [
      'Can lower hairline 2-5 cm depending on scalp laxity',
      'Scar hidden at hairline but visible in some cases',
      'Often combined with hair transplant for feathering',
      'Alternative: hair transplant to lower hairline',
    ],
    sources: ['ASPS', 'RealSelf'],
  },
  {
    id: 'forehead_implant',
    name: 'Forehead/Brow Bone Implant',
    category: 'surgical',
    description: 'Custom implant to augment forehead shape or brow bone',
    howItWorks: 'PEEK or silicone implant placed to add projection to forehead or brow ridge',
    effectiveness: 8,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.3, max: 0.6 },
    costLevel: 'very_high',
    costRange: { min: 10000, max: 25000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '4-8 weeks for swelling, 6 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '2-3 weeks',
    downtime: '1-2 weeks off work',
    painLevel: 'moderate',
    riskLevel: 'medium',
    sideEffects: ['Swelling', 'Numbness', 'Implant visibility', 'Infection'],
    contraindications: ['Very thin skin', 'Unrealistic expectations'],
    targetMetrics: ['brow_ridge', 'forehead_projection', 'facial_convexity'],
    targetIssues: ['flat_forehead', 'weak_brow_ridge', 'feminine_forehead'],
    genderSpecific: 'male',
    permanence: 'permanent',
    anesthesiaType: 'general',
    revisionRate: 0.08,
    regionalCosts: [
      { region: 'USA', min: 12000, max: 25000, currency: 'USD' },
      { region: 'South Korea', min: 8000, max: 18000, currency: 'USD', notes: 'Seoul - custom implants' },
      { region: 'Mexico', min: 6000, max: 14000, currency: 'USD', notes: 'Mexico City - limited availability' },
      { region: 'UK', min: 10000, max: 22000, currency: 'GBP' },
      { region: 'Germany', min: 11000, max: 23000, currency: 'EUR' },
      { region: 'Spain', min: 8000, max: 18000, currency: 'EUR' },
      { region: 'Thailand', min: 6000, max: 14000, currency: 'USD', notes: 'Bangkok - growing expertise' },
      { region: 'Brazil', min: 7000, max: 16000, currency: 'USD', notes: 'Sao Paulo' },
    ],
    surgeonRecommendations: [
      { name: 'Dr. Barry Eppley', location: 'Indianapolis, USA', specialty: 'Custom facial implants', costRange: '$15,000-25,000' },
    ],
    notes: [
      'Custom implants designed from CT scan',
      'Can create more masculine brow ridge',
      'FFS (facial feminization) does the opposite - reduces brow bone',
    ],
    sources: ['Dr. Eppley publications'],
  },

  // ============================================
  // LIP SURGERIES
  // ============================================
  {
    id: 'lip_lift',
    name: 'Lip Lift (Bullhorn Lip Lift)',
    category: 'surgical',
    description: 'Shortening of the philtrum to increase upper lip show',
    howItWorks: 'Skin removed from under the nose, pulling the upper lip upward and creating more vermillion show',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.2, max: 0.5 },
    costLevel: 'high',
    costRange: { min: 3500, max: 8000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '2-4 weeks for swelling, 3-6 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '1-2 weeks',
    downtime: '5-7 days off work',
    painLevel: 'low',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Numbness', 'Visible scar', 'Over-correction'],
    contraindications: ['Already short philtrum', 'Dark skin (scarring risk)'],
    targetMetrics: ['philtrum_length', 'upper_lip_ratio', 'vermillion_show'],
    targetIssues: ['long_philtrum', 'thin_upper_lip', 'aging_lips', 'hidden_vermillion'],
    permanence: 'permanent',
    anesthesiaType: 'local',
    revisionRate: 0.10,
    regionalCosts: [
      { region: 'USA', min: 4000, max: 8000, currency: 'USD' },
      { region: 'Turkey', min: 2000, max: 4000, currency: 'USD' },
      { region: 'Mexico', min: 2000, max: 4000, currency: 'USD', notes: 'Mexico City/Guadalajara' },
      { region: 'UK', min: 3500, max: 7000, currency: 'GBP' },
      { region: 'Germany', min: 3800, max: 7500, currency: 'EUR' },
      { region: 'Spain', min: 2800, max: 5500, currency: 'EUR' },
      { region: 'Thailand', min: 1800, max: 3500, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 2000, max: 4000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    notes: [
      'Ideal philtrum: 11-13mm for women, 13-15mm for men',
      'Removes 3-8mm of skin typically',
      'Scar hidden in nose crease but takes months to mature',
      'Can look unnatural if overdone',
    ],
    sources: ['ASPS', 'RealSelf'],
  },
  {
    id: 'lip_reduction',
    name: 'Lip Reduction',
    category: 'surgical',
    description: 'Surgical reduction of overly large lips',
    howItWorks: 'Excess tissue removed from inside the lip to reduce size while maintaining natural shape',
    effectiveness: 8,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.2, max: 0.5 },
    costLevel: 'medium',
    costRange: { min: 2000, max: 5000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '2-4 weeks for swelling, 3 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '1-2 weeks',
    downtime: '3-5 days off work',
    painLevel: 'low',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Numbness', 'Asymmetry', 'Scarring inside lip'],
    contraindications: ['Unrealistic expectations'],
    targetMetrics: ['lip_ratio', 'vermillion_height', 'facial_harmony'],
    targetIssues: ['overly_large_lips', 'disproportionate_lips', 'lip_asymmetry'],
    permanence: 'permanent',
    anesthesiaType: 'local',
    revisionRate: 0.08,
    regionalCosts: [
      { region: 'USA', min: 2500, max: 5000, currency: 'USD' },
      { region: 'Turkey', min: 1500, max: 3000, currency: 'USD' },
      { region: 'Mexico', min: 1300, max: 2800, currency: 'USD', notes: 'Mexico City/Tijuana' },
      { region: 'UK', min: 2000, max: 4000, currency: 'GBP' },
      { region: 'Germany', min: 2200, max: 4500, currency: 'EUR' },
      { region: 'Spain', min: 1800, max: 3500, currency: 'EUR' },
      { region: 'Thailand', min: 1200, max: 2500, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 1500, max: 3000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    notes: [
      'Incision hidden inside lip',
      'Can be done on upper, lower, or both lips',
      'Less common than lip augmentation',
    ],
    sources: ['ASPS', 'RealSelf'],
  },

  // ============================================
  // OTHER FACIAL SURGERIES
  // ============================================
  {
    id: 'buccal_fat_removal',
    name: 'Buccal Fat Removal',
    category: 'surgical',
    description: 'Removal of buccal fat pads to slim the cheeks',
    howItWorks: 'Fat pads in lower cheeks removed through small intraoral incision',
    effectiveness: 7,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.2, max: 0.5 },
    costLevel: 'medium',
    costRange: { min: 2500, max: 6000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '2-4 weeks for swelling, 3-6 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '1-2 weeks',
    downtime: '3-5 days off work',
    painLevel: 'low',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Asymmetry', 'Facial nerve injury (rare)', 'Over-removal leading to gaunt look'],
    contraindications: ['Thin face', 'Older patients', 'Patients with significant weight fluctuations'],
    targetMetrics: ['cheek_fullness', 'facial_width', 'jawline_definition'],
    targetIssues: ['chubby_cheeks', 'round_face', 'undefined_cheekbones'],
    ageRestrictions: { max: 40 },
    permanence: 'permanent',
    anesthesiaType: 'local',
    revisionRate: 0.05,
    regionalCosts: [
      { region: 'USA', min: 3000, max: 6000, currency: 'USD' },
      { region: 'Turkey', min: 1500, max: 3000, currency: 'USD' },
      { region: 'Mexico', min: 2000, max: 4000, currency: 'USD', notes: 'Mexico City/Tijuana' },
      { region: 'UK', min: 2500, max: 5000, currency: 'GBP' },
      { region: 'Germany', min: 2800, max: 5500, currency: 'EUR' },
      { region: 'Spain', min: 2000, max: 4000, currency: 'EUR' },
      { region: 'Thailand', min: 1500, max: 3000, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 2000, max: 4000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro - popular for facial contouring' },
    ],
    notes: [
      'Controversial procedure - natural fat loss with age may cause gaunt look',
      'Best for younger patients with genetically full cheeks',
      'Face naturally loses fat with age - consider this carefully',
      'Many celebrities have reportedly regretted this procedure',
    ],
    sources: ['ASPS', 'RealSelf'],
  },
  {
    id: 'hair_transplant_fue',
    name: 'FUE Hair Transplant',
    category: 'surgical',
    description: 'Follicular Unit Extraction for permanent hair restoration',
    howItWorks: 'Individual hair follicles extracted from donor area and transplanted to balding areas',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.3, max: 1.0 },
    costLevel: 'very_high',
    costRange: { min: 4000, max: 20000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '6-12 months for growth, 12-18 months final',
    resultsDuration: 'Permanent (transplanted hairs)',
    maintenanceRequired: true,
    maintenanceFrequency: 'Finasteride/minoxidil to protect native hair',
    recoveryTime: '1-2 weeks',
    downtime: '3-7 days off work',
    painLevel: 'low',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Scabbing', 'Shock loss', 'Scarring in donor area', 'Unnatural appearance if poorly done'],
    contraindications: ['Insufficient donor hair', 'Unrealistic expectations', 'Active hair loss without stabilization'],
    targetMetrics: ['hairline', 'hair_density', 'overall_harmony'],
    targetIssues: ['male_pattern_baldness', 'receding_hairline', 'hair_loss', 'thin_hair'],
    genderSpecific: 'male',
    permanence: 'permanent',
    anesthesiaType: 'local',
    revisionRate: 0.15,
    regionalCosts: [
      { region: 'USA', min: 8000, max: 20000, currency: 'USD' },
      { region: 'Turkey', min: 2000, max: 5000, currency: 'USD', notes: 'World capital of hair transplants - 500k+/year' },
      { region: 'Mexico', min: 3500, max: 8000, currency: 'USD', notes: 'Tijuana/Mexico City - growing reputation' },
      { region: 'UK', min: 6000, max: 15000, currency: 'GBP' },
      { region: 'Germany', min: 5500, max: 14000, currency: 'EUR' },
      { region: 'Spain', min: 4000, max: 10000, currency: 'EUR', notes: 'Madrid - emerging destination' },
      { region: 'Thailand', min: 3000, max: 6000, currency: 'USD', notes: 'Bangkok medical tourism hub - growing reputation' },
      { region: 'Brazil', min: 4000, max: 8000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    surgeonRecommendations: [
      { name: 'Dr. Koray Erdogan', location: 'Istanbul, Turkey', specialty: 'Large graft counts', costRange: '$3,000-6,000' },
      { name: 'Dr. Rahal', location: 'Ottawa, Canada', specialty: 'Natural hairlines', costRange: '$10,000-20,000' },
      { name: 'Dr. William Rassman', location: 'Los Angeles, USA', specialty: 'FUE pioneer', costRange: '$8,000-15,000' },
    ],
    notes: [
      'Turkey is the world leader in hair transplants - 500,000+ procedures/year',
      'Must stabilize hair loss with finasteride first',
      'Average: 2500-4000 grafts per session',
      'May need 2+ sessions for full coverage',
      'Transplanted hairs are DHT-resistant and permanent',
    ],
    sources: ['ISHRS', 'RealSelf', 'Tressless community'],
  },
  {
    id: 'otoplasty',
    name: 'Otoplasty (Ear Pinning)',
    category: 'surgical',
    description: 'Reshaping and repositioning of protruding ears',
    howItWorks: 'Cartilage is reshaped through incisions behind the ear to bring ears closer to head',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.2, max: 0.5 },
    costLevel: 'medium',
    costRange: { min: 3000, max: 8000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '2-4 weeks for swelling, 6 months final',
    resultsDuration: 'Permanent',
    maintenanceRequired: false,
    recoveryTime: '1-2 weeks',
    downtime: '1 week off work',
    painLevel: 'low',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Bruising', 'Asymmetry', 'Numbness', 'Overcorrection'],
    contraindications: ['Unrealistic expectations', 'Blood thinners'],
    targetMetrics: ['ear_protrusion', 'facial_harmony'],
    targetIssues: ['protruding_ears', 'ear_asymmetry', 'large_ears'],
    permanence: 'permanent',
    anesthesiaType: 'local',
    revisionRate: 0.05,
    regionalCosts: [
      { region: 'USA', min: 4000, max: 8000, currency: 'USD' },
      { region: 'Turkey', min: 2000, max: 4000, currency: 'USD' },
      { region: 'Mexico', min: 2000, max: 4000, currency: 'USD', notes: 'Mexico City/Guadalajara' },
      { region: 'UK', min: 3000, max: 6000, currency: 'GBP' },
      { region: 'Germany', min: 3500, max: 7000, currency: 'EUR' },
      { region: 'Spain', min: 2500, max: 5000, currency: 'EUR' },
      { region: 'Thailand', min: 1500, max: 3500, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 2000, max: 4500, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro' },
    ],
    notes: [
      'High satisfaction rate - 95%+',
      'Incision hidden behind ear',
      'Headband worn for 6 weeks post-op',
      'Often performed in childhood but can be done at any age',
    ],
    sources: ['ASPS', 'RealSelf'],
  },
  {
    id: 'fat_transfer_face',
    name: 'Facial Fat Transfer (Lipofilling)',
    category: 'surgical',
    description: 'Transfer of your own fat to restore facial volume',
    howItWorks: 'Fat harvested from body via liposuction, processed, and injected into face',
    effectiveness: 7,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.2, max: 0.6 },
    costLevel: 'high',
    costRange: { min: 4000, max: 12000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '3-6 months for final volume (some fat absorbed)',
    resultsDuration: 'Long-lasting (5-10 years) for surviving fat',
    maintenanceRequired: false,
    recoveryTime: '1-2 weeks',
    downtime: '7-10 days off work',
    painLevel: 'moderate',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Bruising', 'Asymmetry', 'Fat necrosis', 'Over/under correction'],
    contraindications: ['Very low body fat', 'Unrealistic expectations'],
    targetMetrics: ['cheek_volume', 'under_eye_hollows', 'overall_harmony'],
    targetIssues: ['volume_loss', 'sunken_cheeks', 'under_eye_hollows', 'aging_face', 'thin_face'],
    permanence: 'semi-permanent',
    anesthesiaType: 'sedation',
    revisionRate: 0.20,
    regionalCosts: [
      { region: 'USA', min: 5000, max: 12000, currency: 'USD' },
      { region: 'Turkey', min: 3000, max: 6000, currency: 'USD' },
      { region: 'Mexico', min: 2500, max: 6000, currency: 'USD', notes: 'Mexico City/Tijuana' },
      { region: 'UK', min: 4000, max: 10000, currency: 'GBP' },
      { region: 'Germany', min: 4500, max: 11000, currency: 'EUR' },
      { region: 'Spain', min: 3500, max: 8000, currency: 'EUR' },
      { region: 'Thailand', min: 2500, max: 5000, currency: 'USD', notes: 'Bangkok medical tourism hub' },
      { region: 'Brazil', min: 3000, max: 6000, currency: 'USD', notes: 'Sao Paulo/Rio de Janeiro - Brazil is world leader in body contouring' },
    ],
    notes: [
      '40-60% of transferred fat survives permanently',
      'Natural result using your own tissue',
      'May need multiple sessions for optimal result',
      'Fat contains stem cells that improve skin quality',
    ],
    sources: ['ASPS', 'RealSelf'],
  },
];

// Helper functions
export function getSurgeryByIssue(issue: string): Surgery[] {
  return SURGICAL_TREATMENTS.filter(s =>
    s.targetIssues.some(i => i.toLowerCase().includes(issue.toLowerCase()))
  );
}

export function getSurgeryByMetric(metric: string): Surgery[] {
  return SURGICAL_TREATMENTS.filter(s =>
    s.targetMetrics.some(m => m.toLowerCase().includes(metric.toLowerCase()))
  );
}

export function getSurgeriesByRiskLevel(maxRisk: 'low' | 'medium' | 'high' | 'very_high'): Surgery[] {
  const riskOrder = ['none', 'very_low', 'low', 'medium', 'high', 'very_high'];
  const maxRiskIndex = riskOrder.indexOf(maxRisk);
  return SURGICAL_TREATMENTS.filter(s => riskOrder.indexOf(s.riskLevel) <= maxRiskIndex);
}

export function getSurgeriesByCostLevel(maxCost: 'low' | 'medium' | 'high' | 'very_high'): Surgery[] {
  const costOrder = ['free', 'low', 'medium', 'high', 'very_high'];
  const maxCostIndex = costOrder.indexOf(maxCost);
  return SURGICAL_TREATMENTS.filter(s => costOrder.indexOf(s.costLevel) <= maxCostIndex);
}

export function getSurgeriesByRegion(region: string): { surgery: Surgery; cost: RegionalCost }[] {
  const results: { surgery: Surgery; cost: RegionalCost }[] = [];
  for (const surgery of SURGICAL_TREATMENTS) {
    const regionCost = surgery.regionalCosts.find(r =>
      r.region.toLowerCase().includes(region.toLowerCase())
    );
    if (regionCost) {
      results.push({ surgery, cost: regionCost });
    }
  }
  return results.sort((a, b) => a.cost.min - b.cost.min);
}

export function getMostEffectiveSurgeries(minEffectiveness: number = 8): Surgery[] {
  return SURGICAL_TREATMENTS
    .filter(s => s.effectiveness >= minEffectiveness)
    .sort((a, b) => b.pslImprovement.max - a.pslImprovement.max);
}
