/**
 * Metric Configurations for Facial Analysis
 *
 * Contains all 70+ metric definitions for front and side profile analysis.
 * Extracted from harmony-scoring.ts for modularity.
 */

import { MetricConfig } from '@/lib/harmony-scoring';
import { BEZIER_CURVES } from '@/lib/bezier-curves';

// ============================================
// METRIC CONFIGURATIONS (70+ METRICS)
// ============================================

export const METRIC_CONFIGS: Record<string, MetricConfig> = {
  // ==========================================
  // FRONT PROFILE - FACIAL PROPORTIONS (32)
  // ==========================================

  faceWidthToHeight: {
    id: 'faceWidthToHeight',
    name: 'Face Width to Height Ratio',
    category: 'Midface/Face Shape',
    unit: 'ratio',
    idealMin: 1.96,
    idealMax: 2.0,
    rangeMin: 1.4,
    rangeMax: 2.5,
    decayRate: 0.12,  //  was 6.4 (53x too harsh)
    maxScore: 30,  //  highest priority metric
    weight: 0.06,
    description: 'Ratio of bizygomatic width to upper face height',
    profileType: 'front',
    customCurve: BEZIER_CURVES.faceWidthToHeight,
  },

  lowerThirdProportion: {
    id: 'lowerThirdProportion',
    name: 'Lower Third Proportion',
    category: 'Midface/Face Shape',
    unit: 'percent',
    idealMin: 31,
    idealMax: 33.5,
    rangeMin: 24,
    rangeMax: 40,
    decayRate: 0.18,  //  was 1.86 (10x too harsh)
    maxScore: 10,
    weight: 0.03,
    description: 'Percentage of face occupied by lower third (subnasale to menton)',
    profileType: 'front',
    customCurve: BEZIER_CURVES.lowerThirdProportion,
  },

  lowerThirdProportionAlt: {
    id: 'lowerThirdProportionAlt',
    name: 'Lower Third Internal Ratio',
    category: 'Midface/Face Shape',
    unit: 'percent',
    idealMin: 33.9,
    idealMax: 37,
    rangeMin: 25,
    rangeMax: 46,
    decayRate: 0.18,  //  was 1.5 (8x too harsh)
    maxScore: 10,
    weight: 0.02,
    description: 'Ratio of upper-lower-third (subnasale to stomion) to total lower third (subnasale to menton)',
    profileType: 'front',
    customCurve: BEZIER_CURVES.lowerThirdProportionAlt,
  },

  middleThirdProportion: {
    id: 'middleThirdProportion',
    name: 'Middle Third Proportion',
    category: 'Midface/Face Shape',
    unit: 'percent',
    idealMin: 31.4,
    idealMax: 33.4,
    rangeMin: 24,
    rangeMax: 42,
    decayRate: 0.18,  //  was 1.5 (8x too harsh)
    maxScore: 10,
    weight: 0.03,
    description: 'Percentage of face occupied by middle third',
    profileType: 'front',
    customCurve: BEZIER_CURVES.middleThirdProportion,
  },

  upperThirdProportion: {
    id: 'upperThirdProportion',
    name: 'Upper Third Proportion',
    category: 'Midface/Face Shape',
    unit: 'percent',
    idealMin: 30,
    idealMax: 32,
    rangeMin: 24,
    rangeMax: 42,
    decayRate: 0.18,  //  was 1.2 (7x too harsh)
    maxScore: 10,
    weight: 0.02,
    description: 'Percentage of face occupied by upper third (trichion to glabella)',
    profileType: 'front',
    customCurve: BEZIER_CURVES.upperThirdProportion,
  },

  bitemporalWidth: {
    id: 'bitemporalWidth',
    name: 'Bitemporal Width',
    category: 'Midface/Face Shape',
    unit: 'percent',
    idealMin: 86.5,
    idealMax: 92.5,
    rangeMin: 75,
    rangeMax: 100,
    decayRate: 0.8,
    maxScore: 10,
    weight: 0.02,
    description: 'Temple width as percentage of bizygomatic width',
    profileType: 'front',
    customCurve: BEZIER_CURVES.bitemporalWidth,
  },

  cheekboneHeight: {
    id: 'cheekboneHeight',
    name: 'Cheekbone Height',
    category: 'Midface/Face Shape',
    unit: 'percent',
    idealMin: 83,
    idealMax: 100,
    rangeMin: 30,
    rangeMax: 140,
    decayRate: 0.5,
    maxScore: 15,  //  higher priority
    weight: 0.03,
    description: 'Vertical position of cheekbones relative to face height',
    profileType: 'front',
    customCurve: BEZIER_CURVES.cheekboneHeight,
  },

  cheekFullness: {
    id: 'cheekFullness',
    name: 'Cheek Fullness',
    category: 'Midface/Face Shape',
    unit: 'ratio',
    idealMin: 1.0,
    idealMax: 1.8,
    rangeMin: 0.3,
    rangeMax: 4.0,
    decayRate: 0.25,
    maxScore: 10,
    weight: 0.02,
    description: 'Malar convexity - measures cheek volume/fullness relative to face width',
    profileType: 'front',
  },

  totalFacialWidthToHeight: {
    id: 'totalFacialWidthToHeight',
    name: 'Total Facial Width to Height Ratio',
    category: 'Midface/Face Shape',
    unit: 'ratio',
    idealMin: 1.34,
    idealMax: 1.37,
    rangeMin: 1.0,
    rangeMax: 1.7,
    decayRate: 0.15,  //  was 13.2 (88x too harsh)
    maxScore: 25,  // Special: higher max score
    weight: 0.05,
    description: 'Total face height divided by cheek width',
    profileType: 'front',
    customCurve: BEZIER_CURVES.totalFacialWidthToHeight,
  },

  midfaceRatio: {
    id: 'midfaceRatio',
    name: 'Midface Ratio',
    category: 'Midface/Face Shape',
    unit: 'ratio',
    idealMin: 0.97,
    idealMax: 1.0,
    rangeMin: 0.5,
    rangeMax: 1.5,
    decayRate: 0.15,  //  was 31.6 (210x too harsh!)
    maxScore: 12.5,  //  medium-high priority
    weight: 0.04,
    description: 'Midface width to height ratio for facial balance',
    profileType: 'front',
    customCurve: BEZIER_CURVES.midfaceRatio,
  },

  // JAW MEASUREMENTS
  jawSlope: {
    id: 'jawSlope',
    name: 'Jaw Slope',
    category: 'Jaw Shape',
    unit: 'degrees',
    idealMin: 140,
    idealMax: 142.5,
    rangeMin: 120,
    rangeMax: 160,
    decayRate: 0.8,
    maxScore: 10,
    weight: 0.03,
    description: 'Angle of the jawline from gonion to chin',
    profileType: 'front',
    customCurve: BEZIER_CURVES.jawSlope,
  },

  jawFrontalAngle: {
    id: 'jawFrontalAngle',
    name: 'Jaw Frontal Angle',
    category: 'Jaw Shape',
    unit: 'degrees',
    idealMin: 86.5,
    idealMax: 92.5,
    rangeMin: 35,
    rangeMax: 140,
    decayRate: 0.6,
    maxScore: 20,  //  high priority
    weight: 0.04,
    description: 'Angle of jaw corners from frontal view',
    profileType: 'front',
    customCurve: BEZIER_CURVES.jawFrontalAngle,
  },

  bigonialWidth: {
    id: 'bigonialWidth',
    name: 'Bigonial Width',
    category: 'Jaw Shape',
    unit: 'percent',
    idealMin: 87.75,
    idealMax: 91.75,
    rangeMin: 60.25,
    rangeMax: 120.25,
    decayRate: 0.9,
    maxScore: 15,  //  higher priority
    weight: 0.03,
    description: 'Jaw width as percentage of bizygomatic width',
    profileType: 'front',
    customCurve: BEZIER_CURVES.bigonialWidth,
  },

  jawWidthRatio: {
    id: 'jawWidthRatio',
    name: 'Jaw Width to Face Width Ratio',
    category: 'Jaw Shape',
    unit: 'ratio',
    idealMin: 0.75,
    idealMax: 0.82,
    rangeMin: 0.6,
    rangeMax: 0.95,
    decayRate: 0.15,  //  was 25.0 (167x too harsh)
    maxScore: 10,
    weight: 0.03,
    description: 'Bigonial width divided by bizygomatic width',
    profileType: 'front',
  },

  // EYE MEASUREMENTS
  lateralCanthalTilt: {
    id: 'lateralCanthalTilt',
    name: 'Lateral Canthal Tilt',
    category: 'Eyes',
    unit: 'degrees',
    idealMin: 4.0,   // Updated: 4-8 is peak "hunter eyes"
    idealMax: 8.0,
    rangeMin: -5,
    rangeMax: 20,
    decayRate: 0.15,  //  was 1.5 (10x too harsh)
    maxScore: 10,
    weight: 0.04,
    description: 'Angle of eye from inner to outer canthus. Positive tilt is attractive.',
    profileType: 'front',
    customCurve: BEZIER_CURVES.lateralCanthalTilt,
    // DIRECTIONAL SCORING: Higher (positive) tilt is better
    // - Ideal: 4-8 (attractive upswept eyes / "hunter eyes")
    // - Good: 0-4 (neutral to slight positive - still attractive)
    // - Weak: < 0 (negative/droopy tilt - only this is a true weakness)
    polarity: 'higher_is_better',
    safeFloor: 0.0,       // Neutral tilt - anything above is acceptable
    softZoneScore: 8.0,   // "Good" score for 0-4 range
  },

  eyeAspectRatio: {
    id: 'eyeAspectRatio',
    name: 'Eye Aspect Ratio',
    category: 'Eyes',
    unit: 'ratio',
    idealMin: 3.0,
    idealMax: 3.5,
    rangeMin: 0.8,
    rangeMax: 6,
    decayRate: 0.25,
    maxScore: 15,
    weight: 0.03,
    description: 'Eye width divided by eye height',
    profileType: 'front',
    customCurve: BEZIER_CURVES.eyeAspectRatio,
  },

  eyeSeparationRatio: {
    id: 'eyeSeparationRatio',
    name: 'Eye Separation Ratio',
    category: 'Eyes',
    unit: 'percent',
    idealMin: 45.7,
    idealMax: 46.8,
    rangeMin: 35,
    rangeMax: 55,
    decayRate: 0.12,  //  was 2.5 (21x too harsh)
    maxScore: 10,
    weight: 0.03,
    description: 'Intercanthal distance as percentage of bizygomatic width',
    profileType: 'front',
    customCurve: BEZIER_CURVES.eyeSeparationRatio,
  },

  interpupillaryRatio: {
    id: 'interpupillaryRatio',
    name: 'Interpupillary Distance Ratio',
    category: 'Eyes',
    unit: 'percent',
    idealMin: 44,
    idealMax: 48,
    rangeMin: 38,
    rangeMax: 54,
    decayRate: 0.25,
    maxScore: 10,
    weight: 0.02,
    description: 'IPD as percentage of bizygomatic width',
    profileType: 'front',
  },

  interpupillaryMouthWidthRatio: {
    id: 'interpupillaryMouthWidthRatio',
    name: 'Interpupillary-Mouth Width Ratio',
    category: 'Eyes',
    unit: 'ratio',
    idealMin: 0.83,
    idealMax: 0.87,
    rangeMin: 0.6,
    rangeMax: 1.1,
    decayRate: 0.12,  //  was 12.0 (100x too harsh)
    maxScore: 10,
    weight: 0.02,
    description: 'Mouth width divided by interpupillary distance',
    profileType: 'front',
    customCurve: BEZIER_CURVES.interpupillaryMouthWidthRatio,
  },

  oneEyeApartTest: {
    id: 'oneEyeApartTest',
    name: 'One Eye Apart Test',
    category: 'Eyes',
    unit: 'ratio',
    idealMin: 0.95,
    idealMax: 1.0,
    rangeMin: 0.7,
    rangeMax: 1.3,
    decayRate: 0.15,  //  was 20.0 (133x too harsh)
    maxScore: 10,
    weight: 0.02,
    description: 'Intercanthal distance should equal one eye width',
    profileType: 'front',
    customCurve: BEZIER_CURVES.oneEyeApartTest,
  },

  tearTroughDepth: {
    id: 'tearTroughDepth',
    name: 'Tear Trough Depth',
    category: 'Eyes',
    unit: 'mm',
    idealMin: 0.0,
    idealMax: 1.5,
    rangeMin: 0.0,
    rangeMax: 4.0,
    decayRate: 0.30,
    maxScore: 10,
    weight: 0.03,
    description: 'Under-eye hollow depth (infraorbital depression). Lower is better for youthfulness.',
    profileType: 'front',
    polarity: 'lower_is_better',
    safeCeiling: 1.5,  // White standard
    softZoneScore: 7.5,
  },

  upperEyelidExposure: {
    id: 'upperEyelidExposure',
    name: 'Upper Eyelid Exposure',
    category: 'Eyes',
    unit: 'mm',
    idealMin: 0.5,
    idealMax: 2.5,
    rangeMin: 0.0,
    rangeMax: 5.0,
    decayRate: 0.25,
    maxScore: 10,
    weight: 0.02,
    description: 'Visible upper eyelid platform. Too little creates hooded eyes.',
    profileType: 'front',
    polarity: 'balanced',
  },

  // EYEBROW MEASUREMENTS
  eyebrowThickness: {
    id: 'eyebrowThickness',
    name: 'Eyebrow Thickness',
    category: 'Upper Third',
    unit: 'mm',
    idealMin: 2.0,
    idealMax: 4.0,
    rangeMin: 1.0,
    rangeMax: 6.0,
    decayRate: 0.25,
    maxScore: 10,
    weight: 0.02,
    description: 'Eyebrow density and thickness. Higher values indicate fuller, denser brows.',
    profileType: 'front',
    polarity: 'balanced',
  },

  eyebrowDistance: {
    id: 'eyebrowDistance',
    name: 'Inter-Eyebrow Distance',
    category: 'Upper Third',
    unit: 'mm',
    idealMin: 15,
    idealMax: 25,
    rangeMin: 5,
    rangeMax: 40,
    decayRate: 0.25,
    maxScore: 10,
    weight: 0.02,
    description: 'Distance between inner edges of eyebrows. Too low creates unibrow (synophrys).',
    profileType: 'front',
    polarity: 'balanced',
  },

  browLengthRatio: {
    id: 'browLengthRatio',
    name: 'Brow Length to Face Width Ratio',
    category: 'Upper Third',
    unit: 'ratio',  //  ratio not percent
    idealMin: 0.69,
    idealMax: 0.76,
    rangeMin: 0.3,
    rangeMax: 1.1,
    decayRate: 0.25,
    maxScore: 10,
    weight: 0.02,
    description: 'Eyebrow length divided by face width',
    profileType: 'front',
    customCurve: BEZIER_CURVES.browLengthToFaceWidth,
  },

  eyebrowTilt: {
    id: 'eyebrowTilt',
    name: 'Eyebrow Tilt',
    category: 'Upper Third',
    unit: 'degrees',
    idealMin: 6.5,
    idealMax: 11,
    rangeMin: -5,
    rangeMax: 25,
    decayRate: 0.25,
    maxScore: 10,
    weight: 0.02,
    description: 'Angle of eyebrow from head to tail',
    profileType: 'front',
    customCurve: BEZIER_CURVES.eyebrowTilt,
  },

  eyebrowLowSetedness: {
    id: 'eyebrowLowSetedness',
    name: 'Eyebrow Low Setedness',
    category: 'Upper Third',
    unit: 'ratio',
    idealMin: 0,
    idealMax: 0.45,
    rangeMin: -0.2,
    rangeMax: 1.0,
    decayRate: 0.15,  //  was 8.0 (53x too harsh)
    maxScore: 10,
    weight: 0.02,
    description: 'Distance from brow to eye relative to eye height',
    profileType: 'front',
    customCurve: BEZIER_CURVES.eyebrowLowSetedness,
  },

  // NOSE MEASUREMENTS (FRONT)
  nasalIndex: {
    id: 'nasalIndex',
    name: 'Nasal Index',
    category: 'Nose',
    unit: 'percent',
    idealMin: 70,
    idealMax: 85,
    rangeMin: 55,
    rangeMax: 100,
    decayRate: 0.25,
    maxScore: 10,
    weight: 0.02,
    description: 'Nose width divided by nose height x 100',
    profileType: 'front',
    customCurve: BEZIER_CURVES.nasalIndex,
  },

  intercanthalNasalRatio: {
    id: 'intercanthalNasalRatio',
    name: 'Intercanthal-Nasal Width Ratio',
    category: 'Nose',
    unit: 'ratio',
    idealMin: 1.04,
    idealMax: 1.16,
    rangeMin: 0.7,
    rangeMax: 1.5,
    decayRate: 0.12,  //  was 12.0 (100x too harsh)
    maxScore: 10,
    weight: 0.02,
    description: 'Alar width should roughly equal intercanthal distance',
    profileType: 'front',
    customCurve: BEZIER_CURVES.intercanthalNasalRatio,
  },

  noseBridgeWidth: {
    id: 'noseBridgeWidth',
    name: 'Nose Bridge to Nose Width',
    category: 'Nose',
    unit: 'ratio',
    idealMin: 2.06,  //  ratio of bridge to alar width
    idealMax: 2.14,
    rangeMin: 1.05,
    rangeMax: 3.0,
    decayRate: 0.15,  //  was 15.0 (100x too harsh)
    maxScore: 10,
    weight: 0.01,
    description: 'Ratio of nose bridge width to alar base width',
    profileType: 'front',
    customCurve: BEZIER_CURVES.noseBridgeToNoseWidth,
  },

  noseTipPosition: {
    id: 'noseTipPosition',
    name: 'Nose Tip Position',
    category: 'Nose',
    unit: 'mm',
    idealMin: 0.5,
    idealMax: 3.5,
    rangeMin: -7.5,
    rangeMax: 12.5,
    decayRate: 0.25,
    maxScore: 2.5,
    weight: 0.01,
    description: 'Nose tip deviation from facial midline',
    profileType: 'front',
    customCurve: BEZIER_CURVES.noseTipPosition,
  },

  // MOUTH/LIP MEASUREMENTS
  mouthWidthToNoseRatio: {
    id: 'mouthWidthToNoseRatio',
    name: 'Mouth Width to Nose Width Ratio',
    category: 'Lips',
    unit: 'ratio',
    idealMin: 1.43,
    idealMax: 1.51,
    rangeMin: 0.96,
    rangeMax: 1.91,
    decayRate: 0.18,  //  was 18.0 (100x too harsh)
    maxScore: 10,
    weight: 0.03,
    description: 'Mouth width divided by nose width',
    profileType: 'front',
    customCurve: BEZIER_CURVES.mouthToNoseWidthRatio,
  },

  lowerToUpperLipRatio: {
    id: 'lowerToUpperLipRatio',
    name: 'Lower Lip to Upper Lip Ratio',
    category: 'Lips',
    unit: 'ratio',
    idealMin: 1.58,
    idealMax: 1.88,
    rangeMin: -0.98,
    rangeMax: 4.03,
    decayRate: 0.20,  //  was 8.0 (40x too harsh)
    maxScore: 7.5,  //  medium priority
    weight: 0.02,
    description: 'Lower lip height divided by upper lip height',
    profileType: 'front',
    customCurve: BEZIER_CURVES.lipRatio,
  },

  lipRatio: {
    id: 'lipRatio',
    name: 'Lip Ratio',
    category: 'Lips',
    unit: 'ratio',
    idealMin: 1.55,  // From Bezier curve peak
    idealMax: 1.85,
    rangeMin: -0.7,
    rangeMax: 4.1,
    decayRate: 0.20,
    maxScore: 10,
    weight: 0.02,
    description: 'Lower to upper lip ratio for lip fullness balance',
    profileType: 'front',
    customCurve: BEZIER_CURVES.lipRatio,
  },

  cupidsBowDepth: {
    id: 'cupidsBowDepth',
    name: "Cupid's Bow Depth",
    category: 'Lips',
    unit: 'mm',
    idealMin: 2.3,
    idealMax: 4,
    rangeMin: 0,
    rangeMax: 7,
    decayRate: 0.25,
    maxScore: 10,
    weight: 0.01,
    description: "Depth of the cupid's bow curve",
    profileType: 'front',
    customCurve: BEZIER_CURVES.cupidsBowDepth,
  },

  mouthCornerPosition: {
    id: 'mouthCornerPosition',
    name: 'Mouth Corner Position',
    category: 'Lips',
    unit: 'mm',
    idealMin: 0,
    idealMax: 4,
    rangeMin: -5,
    rangeMax: 10,
    decayRate: 0.25,
    maxScore: 10,
    weight: 0.01,
    description: 'Mouth corner vertical position relative to lip center',
    profileType: 'front',
    customCurve: BEZIER_CURVES.mouthCornerPosition,
  },

  // CHIN MEASUREMENTS (FRONT)
  chinToPhiltrumRatio: {
    id: 'chinToPhiltrumRatio',
    name: 'Chin to Philtrum Ratio',
    category: 'Chin',
    unit: 'ratio',
    idealMin: 2.15,
    idealMax: 2.45,
    rangeMin: 0.3,
    rangeMax: 4.5,
    decayRate: 0.10,  //  was 10.0 (100x too harsh)
    maxScore: 12.5,  //  medium-high priority
    weight: 0.02,
    description: 'Chin height divided by philtrum length',
    profileType: 'front',
    customCurve: BEZIER_CURVES.chinToPhiltrumRatio,
  },

  chinWidth: {
    id: 'chinWidth',
    name: 'Chin Width',
    category: 'Chin',
    unit: 'percent',
    idealMin: 35,
    idealMax: 45,
    rangeMin: 25,
    rangeMax: 55,
    decayRate: 0.25,
    maxScore: 10,
    weight: 0.02,
    description: 'Horizontal width of the chin (mental protuberance) as percentage of face width',
    profileType: 'front',
  },

  // OTHER FRONT MEASUREMENTS
  iaaJfaDeviation: {
    id: 'iaaJfaDeviation',
    name: 'Deviation of IAA & JFA',
    category: 'Jaw Shape',
    unit: 'degrees',
    idealMin: 0,
    idealMax: 2.5,
    rangeMin: -25,
    rangeMax: 30,
    decayRate: 0.25,
    maxScore: 10,
    weight: 0.02,
    description: 'Deviation between Ipsilateral Alar Angle and Jaw Frontal Angle',
    profileType: 'front',
    customCurve: BEZIER_CURVES.iaaJfaDeviation,
  },

  ipsilateralAlarAngle: {
    id: 'ipsilateralAlarAngle',
    name: 'Ipsilateral Alar Angle',
    category: 'Nose',
    unit: 'degrees',
    idealMin: 86.5,
    idealMax: 92.5,
    rangeMin: 60,
    rangeMax: 125,
    decayRate: 0.6,
    maxScore: 2.5,  //  low priority
    weight: 0.01,
    description: 'Angle of alar base relative to facial plane',
    profileType: 'front',
    customCurve: BEZIER_CURVES.ipsilateralAlarAngle,
  },

  earProtrusionAngle: {
    id: 'earProtrusionAngle',
    name: 'Ear Protrusion Angle',
    category: 'Ears',
    unit: 'degrees',
    idealMin: 10,
    idealMax: 11.5,
    rangeMin: -25,
    rangeMax: 40,
    decayRate: 1.0,
    maxScore: 10,
    weight: 0.01,
    description: 'Angle of ear protrusion from head',
    profileType: 'front',
    customCurve: BEZIER_CURVES.earProtrusionAngle,
  },

  earProtrusionRatio: {
    id: 'earProtrusionRatio',
    name: 'Ear Protrusion Ratio',
    category: 'Ears',
    unit: 'percent',
    idealMin: 8,
    idealMax: 12,
    rangeMin: -20,
    rangeMax: 40,
    decayRate: 0.8,
    maxScore: 10,
    weight: 0.01,
    description: 'Ear protrusion as percentage of head width',
    profileType: 'front',
    customCurve: BEZIER_CURVES.earProtrusionRatio,
  },

  neckWidth: {
    id: 'neckWidth',
    name: 'Neck Width',
    category: 'Neck',
    unit: 'percent',
    idealMin: 92,
    idealMax: 98,
    rangeMin: 60,
    rangeMax: 120,
    decayRate: 0.6,
    maxScore: 10,
    weight: 0.01,
    description: 'Neck width as percentage of jaw width',
    profileType: 'front',
    customCurve: BEZIER_CURVES.neckWidth,
  },

  // ==========================================
  // SIDE PROFILE MEASUREMENTS (38)
  // ==========================================

  gonialAngle: {
    id: 'gonialAngle',
    name: 'Gonial Angle',
    category: 'Occlusion/Jaw Growth',
    unit: 'degrees',
    idealMin: 115,  //  115-121
    idealMax: 121,
    rangeMin: 90,
    rangeMax: 145,
    decayRate: 0.08,  //  was 0.8 (10x too harsh)
    maxScore: 10,
    weight: 0.04,
    description: 'Angle at the jaw corner (gonion)',
    profileType: 'side',
    customCurve: BEZIER_CURVES.gonialAngle,
  },

  nasolabialAngle: {
    id: 'nasolabialAngle',
    name: 'Nasolabial Angle',
    category: 'Nose',
    unit: 'degrees',
    idealMin: 97,  // Bezier curve peak: 97-114
    idealMax: 114,
    rangeMin: 75,
    rangeMax: 120,
    decayRate: 0.15,  //  was 0.6 (4x too harsh)
    maxScore: 10,
    weight: 0.03,
    description: 'Angle between columella and upper lip',
    profileType: 'side',
    customCurve: BEZIER_CURVES.nasolabialAngle,
  },

  nasofrontalAngle: {
    id: 'nasofrontalAngle',
    name: 'Nasofrontal Angle',
    category: 'Nose',
    unit: 'degrees',
    idealMin: 116,
    idealMax: 128,
    rangeMin: 90,
    rangeMax: 160,
    decayRate: 0.5,
    maxScore: 10,
    weight: 0.02,
    description: 'Angle at the bridge of nose (nasion)',
    profileType: 'side',
    customCurve: BEZIER_CURVES.nasofrontalAngle,
  },

  nasofacialAngle: {
    id: 'nasofacialAngle',
    name: 'Nasofacial Angle',
    category: 'Nose',
    unit: 'degrees',
    idealMin: 31,
    idealMax: 35,
    rangeMin: 15,
    rangeMax: 50,
    decayRate: 0.25,
    maxScore: 10,
    weight: 0.02,
    description: 'Angle between nose and face plane',
    profileType: 'side',
    customCurve: BEZIER_CURVES.nasofacialAngle,
  },

  nasomentaAngle: {
    id: 'nasomentaAngle',
    name: 'Nasomental Angle',
    category: 'Nose',
    unit: 'degrees',
    idealMin: 126,
    idealMax: 131,
    rangeMin: 105,
    rangeMax: 155,
    decayRate: 0.7,
    maxScore: 10,
    weight: 0.02,
    description: 'Angle from nasion to nose tip to chin',
    profileType: 'side',
    customCurve: BEZIER_CURVES.nasomentalAngle,
  },

  nasalTipAngle: {
    id: 'nasalTipAngle',
    name: 'Nasal Tip Angle',
    category: 'Nose',
    unit: 'degrees',
    idealMin: 128.5,  //  128.5-138.5
    idealMax: 138.5,
    rangeMin: 90,
    rangeMax: 170,
    decayRate: 0.8,
    maxScore: 10,
    weight: 0.02,
    description: 'Angle of the nose tip',
    profileType: 'side',
    customCurve: BEZIER_CURVES.nasalTipAngle,
  },

  nasalProjection: {
    id: 'nasalProjection',
    name: 'Nasal Projection',
    category: 'Nose',
    unit: 'ratio',
    idealMin: 0.55,
    idealMax: 0.6,
    rangeMin: 0.4,
    rangeMax: 0.75,
    decayRate: 0.15,  //  was 20.0 (133x too harsh)
    maxScore: 10,
    weight: 0.02,
    description: 'Nose projection relative to nasal length (Goode ratio)',
    profileType: 'side',
    customCurve: BEZIER_CURVES.nasalProjection,
  },

  nasalWToHRatio: {
    id: 'nasalWToHRatio',
    name: 'Nasal W to H Ratio',
    category: 'Nose',
    unit: 'ratio',
    idealMin: 0.67,
    idealMax: 0.78,
    rangeMin: 0.5,
    rangeMax: 0.95,
    decayRate: 0.20,  //  was 15.0 (75x too harsh)
    maxScore: 10,
    weight: 0.01,
    description: 'Nose width to height ratio from side view',
    profileType: 'side',
    customCurve: BEZIER_CURVES.nasalWToHRatio,
  },

  noseTipRotationAngle: {
    id: 'noseTipRotationAngle',
    name: 'Nose Tip Rotation Angle',
    category: 'Nose',
    unit: 'degrees',
    idealMin: 95,
    idealMax: 110,
    rangeMin: 80,
    rangeMax: 125,
    decayRate: 0.8,
    maxScore: 10,
    weight: 0.01,
    description: 'Angle of nose tip rotation',
    profileType: 'side',
    customCurve: BEZIER_CURVES.noseTipRotationAngle,
  },

  frankfortTipAngle: {
    id: 'frankfortTipAngle',
    name: 'Frankfort-Tip Angle',
    category: 'Nose',
    unit: 'degrees',
    idealMin: 28,
    idealMax: 34,
    rangeMin: 20,
    rangeMax: 42,
    decayRate: 1.0,
    maxScore: 10,
    weight: 0.01,
    description: 'Angle between Frankfort plane and nose tip',
    profileType: 'side',
    customCurve: BEZIER_CURVES.frankfortTipAngle,
  },

  mentolabialAngle: {
    id: 'mentolabialAngle',
    name: 'Mentolabial Angle',
    category: 'Lips',
    unit: 'degrees',
    idealMin: 111,  //  111-127
    idealMax: 127,
    rangeMin: 20,
    rangeMax: 200,
    decayRate: 0.5,
    maxScore: 10,
    weight: 0.02,
    description: 'Angle at the labiomental fold',
    profileType: 'side',
    customCurve: BEZIER_CURVES.mentolabialAngle,
  },

  zAngle: {
    id: 'zAngle',
    name: 'Z Angle',
    category: 'Occlusion/Jaw Growth',
    unit: 'degrees',
    idealMin: 75,
    idealMax: 85,
    rangeMin: 60,
    rangeMax: 100,
    decayRate: 0.8,
    maxScore: 10,
    weight: 0.02,
    description: 'Merrifield Z-Angle for profile assessment',
    profileType: 'side',
    customCurve: BEZIER_CURVES.zAngle,
  },

  submentalCervicalAngle: {
    id: 'submentalCervicalAngle',
    name: 'Submental Cervical Angle',
    category: 'Neck',
    unit: 'degrees',
    idealMin: 94,
    idealMax: 106,
    rangeMin: 70,
    rangeMax: 140,
    decayRate: 0.6,
    maxScore: 10,
    weight: 0.02,
    description: 'Angle between chin and neck',
    profileType: 'side',
    customCurve: BEZIER_CURVES.submentalCervicalAngle,
  },

  facialConvexityGlabella: {
    id: 'facialConvexityGlabella',
    name: 'Facial Convexity (Glabella)',
    category: 'Midface/Face Shape',
    unit: 'degrees',
    idealMin: 170,  // Bezier curve: 170-175
    idealMax: 175,
    rangeMin: 150,
    rangeMax: 185,
    decayRate: 0.4,
    maxScore: 10,
    weight: 0.03,
    description: 'Facial convexity angle using glabella',
    profileType: 'side',
    customCurve: BEZIER_CURVES.facialConvexityGlabella,
  },

  facialConvexityNasion: {
    id: 'facialConvexityNasion',
    name: 'Facial Convexity (Nasion)',
    category: 'Midface/Face Shape',
    unit: 'degrees',
    idealMin: 163,  //  163-166
    idealMax: 166,
    rangeMin: 130,
    rangeMax: 190,
    decayRate: 0.4,
    maxScore: 10,
    weight: 0.02,
    description: 'Facial convexity angle using nasion',
    profileType: 'side',
    customCurve: BEZIER_CURVES.facialConvexityNasion,
  },

  totalFacialConvexity: {
    id: 'totalFacialConvexity',
    name: 'Total Facial Convexity',
    category: 'Midface/Face Shape',
    unit: 'degrees',
    idealMin: 140,  // Bezier curve: 140-147
    idealMax: 147,
    rangeMin: 120,
    rangeMax: 160,
    decayRate: 0.5,
    maxScore: 10,
    weight: 0.03,
    description: 'Complete facial profile convexity measurement',
    profileType: 'side',
    customCurve: BEZIER_CURVES.totalFacialConvexity,
  },

  facialDepthToHeight: {
    id: 'facialDepthToHeight',
    name: 'Facial Depth to Height Ratio',
    category: 'Midface/Face Shape',
    unit: 'ratio',
    idealMin: 1.3,
    idealMax: 1.44,
    rangeMin: 0.7,
    rangeMax: 1.8,
    decayRate: 0.15,  //  was 8.0 (53x too harsh)
    maxScore: 10,
    weight: 0.02,
    description: 'Facial depth divided by facial height',
    profileType: 'side',
    customCurve: BEZIER_CURVES.facialDepthToHeightRatio,
  },

  anteriorFacialDepth: {
    id: 'anteriorFacialDepth',
    name: 'Anterior Facial Depth',
    category: 'Midface/Face Shape',
    unit: 'degrees',
    idealMin: 64.5,
    idealMax: 67.5,
    rangeMin: 45,
    rangeMax: 95,
    decayRate: 0.5,
    maxScore: 10,
    weight: 0.01,
    description: 'Anterior facial projection angle',
    profileType: 'side',
    customCurve: BEZIER_CURVES.anteriorFacialDepth,
  },

  interiorMidfaceProjectionAngle: {
    id: 'interiorMidfaceProjectionAngle',
    name: 'Interior Midface Projection Angle',
    category: 'Midface/Face Shape',
    unit: 'degrees',
    idealMin: 50,
    idealMax: 56,
    rangeMin: 30,
    rangeMax: 100,
    decayRate: 0.5,
    maxScore: 10,
    weight: 0.02,
    description: 'Interior midface projection from side profile',
    profileType: 'side',
    customCurve: BEZIER_CURVES.interiorMidfaceProjectionAngle,
  },

  recessionFromFrankfort: {
    id: 'recessionFromFrankfort',
    name: 'Recession Relative to Frankfort Plane',
    category: 'Occlusion/Jaw Growth',
    unit: 'mm',
    idealMin: 1.5,
    idealMax: 15,
    rangeMin: -30,
    rangeMax: 30,
    decayRate: 0.3,
    maxScore: 10,
    weight: 0.02,
    description: 'Chin position relative to Frankfort plane',
    profileType: 'side',
  },

  mandibularPlaneAngle: {
    id: 'mandibularPlaneAngle',
    name: 'Mandibular Plane Angle',
    category: 'Occlusion/Jaw Growth',
    unit: 'degrees',
    idealMin: 15,  //  15-22
    idealMax: 22,
    rangeMin: -15,
    rangeMax: 55,
    decayRate: 0.12,  //  was 0.8 (7x too harsh)
    maxScore: 10,
    weight: 0.03,
    description: 'Angle of mandibular plane to Frankfort plane',
    profileType: 'side',
    customCurve: BEZIER_CURVES.mandibularPlaneAngle,
  },

  ramusToMandibleRatio: {
    id: 'ramusToMandibleRatio',
    name: 'Ramus to Mandible Ratio',
    category: 'Occlusion/Jaw Growth',
    unit: 'ratio',
    idealMin: 0.65,
    idealMax: 0.75,
    rangeMin: 0.5,
    rangeMax: 0.9,
    decayRate: 0.15,  //  was 15.0 (100x too harsh)
    maxScore: 10,
    weight: 0.02,
    description: 'Ramus height divided by mandible length',
    profileType: 'side',
    customCurve: BEZIER_CURVES.ramusToMandibleRatio,
  },

  gonionToMouthLine: {
    id: 'gonionToMouthLine',
    name: 'Gonion to Mouth Line',
    category: 'Jaw Shape',
    unit: 'mm',
    idealMin: 15,  //  15-45mm
    idealMax: 45,
    rangeMin: -20,
    rangeMax: 65,
    decayRate: 0.5,
    maxScore: 10,
    weight: 0.02,
    description: 'Distance from gonion to mouth level line',
    profileType: 'side',
    customCurve: BEZIER_CURVES.gonionToMouthLine,
  },

  // E-LINE MEASUREMENTS
  eLineUpperLip: {
    id: 'eLineUpperLip',
    name: 'Upper Lip E-Line Position',
    category: 'Lips',
    unit: 'mm',
    idealMin: 1.5,  //  positive = in front of E-line
    idealMax: 5.5,
    rangeMin: -8,
    rangeMax: 14,
    decayRate: 0.30,  //  was 1.0 (3x too harsh)
    maxScore: 10,
    weight: 0.02,
    description: 'Upper lip distance from E-line (Ricketts). Positive = in front.',
    profileType: 'side',
    customCurve: BEZIER_CURVES.eLineUpperLip,
  },

  eLineLowerLip: {
    id: 'eLineLowerLip',
    name: 'Lower Lip E-Line Position',
    category: 'Lips',
    unit: 'mm',
    idealMin: 1.4,  //  positive = in front of E-line
    idealMax: 4.1,
    rangeMin: -8,
    rangeMax: 12,
    decayRate: 0.30,  //  was 1.0 (3x too harsh)
    maxScore: 10,
    weight: 0.02,
    description: 'Lower lip distance from E-line (Ricketts). Positive = in front.',
    profileType: 'side',
    customCurve: BEZIER_CURVES.eLineLowerLip,
  },

  // S-LINE MEASUREMENTS
  sLineUpperLip: {
    id: 'sLineUpperLip',
    name: 'Upper Lip S-Line Position',
    category: 'Lips',
    unit: 'mm',
    idealMin: 0,
    idealMax: 3,
    rangeMin: -5,
    rangeMax: 8,
    decayRate: 0.25,
    maxScore: 10,
    weight: 0.01,
    description: 'Upper lip distance from S-line (Steiner)',
    profileType: 'side',
    customCurve: BEZIER_CURVES.sLineUpperLip,
  },

  sLineLowerLip: {
    id: 'sLineLowerLip',
    name: 'Lower Lip S-Line Position',
    category: 'Lips',
    unit: 'mm',
    idealMin: -0.4,
    idealMax: 0.4,
    rangeMin: -8,
    rangeMax: 6,
    decayRate: 0.25,  //  was 3.0 (12x too harsh)
    maxScore: 10,
    weight: 0.01,
    description: 'Lower lip distance from S-line (Steiner)',
    profileType: 'side',
    customCurve: BEZIER_CURVES.sLineLowerLip,
  },

  // BURSTONE LINE
  burstoneUpperLip: {
    id: 'burstoneUpperLip',
    name: 'Upper Lip Burstone Line',
    category: 'Lips',
    unit: 'mm',
    idealMin: -4.7,  //  negative = behind Burstone line
    idealMax: -2.3,
    rangeMin: -15,
    rangeMax: 10,
    decayRate: 1.0,
    maxScore: 10,
    weight: 0.01,
    description: 'Upper lip to Burstone line distance. Negative = behind.',
    profileType: 'side',
    customCurve: BEZIER_CURVES.burstoneUpperLip,
  },

  burstoneLowerLip: {
    id: 'burstoneLowerLip',
    name: 'Lower Lip Burstone Line',
    category: 'Lips',
    unit: 'mm',
    idealMin: -2.8,  //  negative = behind Burstone line
    idealMax: -1.2,
    rangeMin: -10,
    rangeMax: 10,
    decayRate: 1.0,
    maxScore: 10,
    weight: 0.01,
    description: 'Lower lip to Burstone line distance. Negative = behind.',
    profileType: 'side',
    customCurve: BEZIER_CURVES.burstoneLowerLip,
  },

  // H LINE
  holdawayHLine: {
    id: 'holdawayHLine',
    name: 'Holdaway H Line',
    category: 'Lips',
    unit: 'mm',
    idealMin: 0,
    idealMax: 4,
    rangeMin: -5,
    rangeMax: 10,
    decayRate: 0.8,
    maxScore: 10,
    weight: 0.01,
    description: 'Holdaway H-line soft tissue assessment',
    profileType: 'side',
    customCurve: BEZIER_CURVES.holdawayHLine,
  },

  // CHIN MEASUREMENTS (SIDE)
  chinProjection: {
    id: 'chinProjection',
    name: 'Chin Projection',
    category: 'Chin',
    unit: 'mm',
    idealMin: -3,
    idealMax: 3,
    rangeMin: -12,
    rangeMax: 12,
    decayRate: 0.8,
    maxScore: 10,
    weight: 0.02,
    description: 'Chin projection relative to ideal position',
    profileType: 'side',
  },

  recessionRelativeToFrankfort: {
    id: 'recessionRelativeToFrankfort',
    name: 'Recession Relative to Frankfort Plane',
    category: 'Chin',
    unit: 'mm',
    idealMin: -2,
    idealMax: 2,
    rangeMin: -10,
    rangeMax: 10,
    decayRate: 0.8,
    maxScore: 10,
    weight: 0.02,
    description: 'Chin recession relative to Frankfort horizontal',
    profileType: 'side',
    customCurve: BEZIER_CURVES.recessionRelativeToFrankfort,
  },

  // FOREHEAD
  browridgeInclinationAngle: {
    id: 'browridgeInclinationAngle',
    name: 'Browridge Inclination Angle',
    category: 'Upper Third',
    unit: 'degrees',
    idealMin: 15,  //  15-22
    idealMax: 22,
    rangeMin: -5,
    rangeMax: 46,
    decayRate: 1.0,
    maxScore: 10,
    weight: 0.02,
    description: 'Angle of the brow ridge from profile',
    profileType: 'side',
    customCurve: BEZIER_CURVES.browridgeInclinationAngle,
  },

  upperForeheadSlope: {
    id: 'upperForeheadSlope',
    name: 'Upper Forehead Slope',
    category: 'Upper Third',
    unit: 'degrees',
    idealMin: 0,  //  0-2
    idealMax: 2,
    rangeMin: -15,
    rangeMax: 15,
    decayRate: 0.25,
    maxScore: 10,
    weight: 0.01,
    description: 'Slope angle of the upper forehead',
    profileType: 'side',
    customCurve: BEZIER_CURVES.upperForeheadSlope,
  },

  // MIDFACE PROJECTION
  midfaceProjectionAngle: {
    id: 'midfaceProjectionAngle',
    name: 'Interior Midface Projection Angle',
    category: 'Midface/Face Shape',
    unit: 'degrees',
    idealMin: 85,
    idealMax: 95,
    rangeMin: 75,
    rangeMax: 105,
    decayRate: 0.8,
    maxScore: 10,
    weight: 0.02,
    description: 'Angle of midface projection from profile',
    profileType: 'side',
  },

  orbitalVector: {
    id: 'orbitalVector',
    name: 'Orbital Vector',
    category: 'Eyes',
    unit: 'mm',
    idealMin: 0,
    idealMax: 4,
    rangeMin: -6,
    rangeMax: 10,
    decayRate: 1.0,
    maxScore: 10,
    weight: 0.02,
    description: 'Relationship of globe to orbital rim',
    profileType: 'side',
    customCurve: BEZIER_CURVES.orbitalVector,
  },

  skinUniformity: {
    id: 'skinUniformity',
    name: 'Skin Uniformity',
    category: 'Skin Quality',
    unit: 'ratio',
    idealMin: 0.90,
    idealMax: 1.00,
    rangeMin: 0.50,
    rangeMax: 1.00,
    decayRate: 0.20,  //  was 5.0 (25x too harsh)
    maxScore: 10,
    weight: 0.02,
    description: 'Skin tone evenness and hyperpigmentation. 1.0 = perfectly uniform.',
    profileType: 'front',
    polarity: 'higher_is_better',
    safeFloor: 0.85,  // Acceptable uniformity threshold
    softZoneScore: 7.5,
  },

};

// ============================================
// MEASUREMENT CATEGORIES
// ============================================

export const MEASUREMENT_CATEGORIES = {
  'Midface/Face Shape': { color: '#67e8f9', weight: 0.20 },
  'Occlusion/Jaw Growth': { color: '#a78bfa', weight: 0.15 },
  'Jaw Shape': { color: '#f97316', weight: 0.13 },
  'Upper Third': { color: '#84cc16', weight: 0.08 },
  'Eyes': { color: '#06b6d4', weight: 0.12 },
  'Nose': { color: '#fbbf24', weight: 0.10 },
  'Lips': { color: '#ec4899', weight: 0.10 },
  'Chin': { color: '#ef4444', weight: 0.06 },
  'Neck': { color: '#14b8a6', weight: 0.03 },
  'Other': { color: '#6b7280', weight: 0.03 },
};
