/**
 * Non-Surgical Procedures Database
 * Minimally invasive treatments: injectables, skin treatments, energy devices
 */

import { Treatment } from './types';

export const NON_SURGICAL_TREATMENTS: Treatment[] = [
  // ============================================
  // DERMAL FILLERS
  // ============================================
  {
    id: 'lip_filler',
    name: 'Lip Filler (Hyaluronic Acid)',
    category: 'minimally_invasive',
    description: 'Injectable filler to add volume and definition to lips',
    howItWorks: 'Hyaluronic acid gel injected into lips attracts water and adds volume',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.1, max: 0.4 },
    costLevel: 'medium',
    costRange: { min: 500, max: 1500, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: 'Immediate (final results after swelling subsides in 1-2 weeks)',
    resultsDuration: '6-12 months',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 6-12 months',
    recoveryTime: '1-3 days',
    downtime: 'Minimal - can return to work same day',
    painLevel: 'moderate',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Bruising', 'Asymmetry', 'Lumps', 'Tyndall effect (rare)'],
    contraindications: ['Active cold sores', 'Pregnancy', 'Autoimmune disorders'],
    targetMetrics: ['lip_ratio', 'vermillion_height', 'cupids_bow'],
    targetIssues: ['thin_lips', 'asymmetric_lips', 'aging_lips', 'undefined_cupids_bow'],
    notes: [
      'Start conservative - can always add more',
      'Juvederm, Restylane, and Belotero are common brands',
      'Hyaluronidase can dissolve if needed',
      '0.5-1ml is typical for natural enhancement',
      'Avoid exercise and alcohol 24 hours after',
    ],
    sources: ['ASPS', 'Journal of Cosmetic Dermatology'],
  },
  {
    id: 'chin_filler',
    name: 'Chin Filler',
    category: 'minimally_invasive',
    description: 'Injectable filler to add projection and definition to chin',
    howItWorks: 'HA or calcium hydroxylapatite (Radiesse) filler adds volume to chin',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.2, max: 0.5 },
    costLevel: 'medium',
    costRange: { min: 600, max: 1800, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: 'Immediate',
    resultsDuration: '12-24 months (Radiesse lasts longer)',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 12-24 months',
    recoveryTime: '1-3 days',
    downtime: 'Minimal',
    painLevel: 'low',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Bruising', 'Asymmetry', 'Vascular occlusion (rare)'],
    contraindications: ['Active skin infections', 'Bleeding disorders'],
    targetMetrics: ['chin_projection', 'profile_harmony', 'pogonion'],
    targetIssues: ['recessed_chin', 'weak_chin', 'short_chin'],
    notes: [
      'Radiesse stimulates collagen and lasts longer',
      'Non-reversible filler (Radiesse) - ensure injector is experienced',
      'Can add 5-10mm of projection',
      'Often combined with jawline filler',
    ],
    sources: ['ASPS', 'Dermatologic Surgery'],
  },
  {
    id: 'jawline_filler',
    name: 'Jawline Filler (Jaw Contouring)',
    category: 'minimally_invasive',
    description: 'Injectable filler along jawline for definition and contour',
    howItWorks: 'Filler placed along mandible creates sharper jawline definition',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.2, max: 0.6 },
    costLevel: 'high',
    costRange: { min: 1000, max: 3500, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: 'Immediate',
    resultsDuration: '12-24 months',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 12-24 months',
    recoveryTime: '1-5 days',
    downtime: 'Minimal - some swelling',
    painLevel: 'moderate',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Bruising', 'Asymmetry', 'Vascular occlusion (rare)'],
    contraindications: ['Active skin infections', 'Unrealistic expectations'],
    targetMetrics: ['gonial_angle', 'jaw_width_ratio', 'profile_harmony'],
    targetIssues: ['undefined_jawline', 'weak_gonial_angle', 'jowls'],
    notes: [
      'Requires significant volume (2-4 syringes)',
      'Radiesse or thicker HA fillers work best',
      'Male jawline typically requires more angular placement',
      'Can lift mild jowls by adding structure',
    ],
    sources: ['ASPS', 'Aesthetic Surgery Journal'],
  },
  {
    id: 'cheek_filler',
    name: 'Cheek Filler (Midface Volume)',
    category: 'minimally_invasive',
    description: 'Injectable filler to enhance cheekbone projection and midface volume',
    howItWorks: 'Filler placed on malar bone or submalar area adds projection and lift',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.2, max: 0.5 },
    costLevel: 'medium',
    costRange: { min: 800, max: 2000, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: 'Immediate',
    resultsDuration: '12-18 months',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 12-18 months',
    recoveryTime: '1-5 days',
    downtime: 'Minimal - some swelling',
    painLevel: 'moderate',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Bruising', 'Asymmetry', 'Migration'],
    contraindications: ['Active infections', 'Malar rash'],
    targetMetrics: ['cheekbone_projection', 'fwhr', 'midface_ratio'],
    targetIssues: ['flat_cheeks', 'midface_deficiency', 'volume_loss', 'aging_face'],
    notes: [
      'Strategic placement can lift entire face',
      'Voluma and Radiesse are commonly used',
      'Can create "model cheekbones" with proper technique',
      'Often combined with under-eye filler',
    ],
    sources: ['ASPS', 'Dermatologic Surgery'],
  },
  {
    id: 'under_eye_filler',
    name: 'Under Eye Filler (Tear Trough)',
    category: 'minimally_invasive',
    description: 'Injectable filler to correct under-eye hollows and dark circles',
    howItWorks: 'Soft HA filler placed in tear trough blends the under-eye to cheek junction',
    effectiveness: 7,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.1, max: 0.3 },
    costLevel: 'medium',
    costRange: { min: 600, max: 1500, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: 'Immediate',
    resultsDuration: '12-18 months',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 12-18 months',
    recoveryTime: '3-7 days',
    downtime: 'Swelling and bruising common',
    painLevel: 'moderate',
    riskLevel: 'medium',
    sideEffects: ['Swelling', 'Bruising', 'Tyndall effect (blue tint)', 'Lumps', 'Blindness (very rare)'],
    contraindications: ['Malar edema', 'Festoons', 'Very thin skin'],
    targetMetrics: ['infraorbital_area', 'tear_trough'],
    targetIssues: ['dark_circles', 'under_eye_hollows', 'tear_trough_deformity'],
    notes: [
      'High-risk area - choose experienced injector',
      'Light, thin fillers only (Belotero, Restylane Silk)',
      'Cannula technique safer than needle',
      'Not suitable for fat pads or festoons - may need surgery',
    ],
    sources: ['ASPS', 'Plastic and Reconstructive Surgery'],
  },
  {
    id: 'nose_filler',
    name: 'Non-Surgical Rhinoplasty (Nose Filler)',
    category: 'minimally_invasive',
    description: 'Injectable filler to reshape nose without surgery',
    howItWorks: 'Filler strategically placed to smooth bumps, lift tip, or straighten profile',
    effectiveness: 7,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.1, max: 0.3 },
    costLevel: 'medium',
    costRange: { min: 600, max: 1500, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: 'Immediate',
    resultsDuration: '12-18 months',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 12-18 months',
    recoveryTime: '1-3 days',
    downtime: 'Minimal',
    painLevel: 'moderate',
    riskLevel: 'high',
    sideEffects: ['Swelling', 'Bruising', 'Asymmetry', 'Skin necrosis (rare)', 'Blindness (very rare)'],
    contraindications: ['Previous rhinoplasty', 'Very thin skin', 'Desire for size reduction'],
    targetMetrics: ['nasal_bridge', 'nasal_tip', 'nasolabial_angle'],
    targetIssues: ['dorsal_hump', 'crooked_nose', 'droopy_tip', 'flat_bridge'],
    notes: [
      'Cannot make nose smaller - only camouflages',
      'Highest risk area for vascular occlusion',
      'Only experienced injectors should perform',
      'Good for testing rhinoplasty results before surgery',
      'HA filler preferred (reversible with hyaluronidase)',
    ],
    sources: ['ASPS', 'Dermatologic Surgery'],
  },
  {
    id: 'temple_filler',
    name: 'Temple Filler',
    category: 'minimally_invasive',
    description: 'Injectable filler to restore temple volume',
    howItWorks: 'Filler placed in temporal fossa restores youthful convexity',
    effectiveness: 7,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.1, max: 0.2 },
    costLevel: 'medium',
    costRange: { min: 600, max: 1200, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: 'Immediate',
    resultsDuration: '12-18 months',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 12-18 months',
    recoveryTime: '1-3 days',
    downtime: 'Minimal',
    painLevel: 'low',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Bruising'],
    contraindications: ['Active infections'],
    targetMetrics: ['temple_volume', 'upper_face_harmony'],
    targetIssues: ['hollow_temples', 'aging_face', 'gaunt_appearance'],
    notes: [
      'Often overlooked but very rejuvenating',
      'Restores heart-shaped face appearance',
      'Deep injection technique minimizes risk',
    ],
    sources: ['ASPS'],
  },

  // ============================================
  // NEUROMODULATORS (BOTOX)
  // ============================================
  {
    id: 'botox_forehead',
    name: 'Botox - Forehead & Frown Lines',
    category: 'minimally_invasive',
    description: 'Botulinum toxin to relax forehead muscles and reduce wrinkles',
    howItWorks: 'Blocks nerve signals to muscles, preventing contraction and smoothing lines',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.1, max: 0.3 },
    costLevel: 'medium',
    costRange: { min: 200, max: 600, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: '3-7 days for onset, 2 weeks for full effect',
    resultsDuration: '3-4 months',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 3-4 months',
    recoveryTime: 'None',
    downtime: 'None - can return to activities immediately',
    painLevel: 'low',
    riskLevel: 'very_low',
    sideEffects: ['Bruising', 'Headache', 'Brow ptosis (temporary)', 'Heaviness'],
    contraindications: ['Pregnancy', 'Neuromuscular disorders', 'Active infection'],
    targetMetrics: ['forehead_wrinkles', 'glabella'],
    targetIssues: ['forehead_lines', 'frown_lines', 'eleven_lines', 'resting_angry_face'],
    notes: [
      'Botox, Dysport, Xeomin, Jeuveau are all options',
      'Preventative Botox popular in 20s-30s',
      'Start conservative to avoid frozen look',
      'Results improve with regular treatment',
    ],
    sources: ['FDA', 'ASPS'],
  },
  {
    id: 'botox_crows_feet',
    name: "Botox - Crow's Feet",
    category: 'minimally_invasive',
    description: 'Botulinum toxin to reduce wrinkles around the eyes',
    howItWorks: 'Relaxes orbicularis oculi muscle to smooth lateral canthal lines',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.1, max: 0.2 },
    costLevel: 'low',
    costRange: { min: 150, max: 400, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: '3-7 days',
    resultsDuration: '3-4 months',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 3-4 months',
    recoveryTime: 'None',
    downtime: 'None',
    painLevel: 'low',
    riskLevel: 'very_low',
    sideEffects: ['Bruising', 'Temporary weakness of smile'],
    contraindications: ['Pregnancy', 'Neuromuscular disorders'],
    targetMetrics: ['periorbital_area'],
    targetIssues: ['crows_feet', 'eye_wrinkles', 'smile_lines'],
    notes: [
      'Very safe and effective area for Botox',
      'Natural result when done conservatively',
      'Often combined with forehead treatment',
    ],
    sources: ['FDA', 'ASPS'],
  },
  {
    id: 'botox_masseter',
    name: 'Botox - Masseter (Jaw Slimming)',
    category: 'minimally_invasive',
    description: 'Botulinum toxin to slim the lower face by reducing masseter muscle',
    howItWorks: 'Relaxes masseter muscle, causing it to atrophy and slim the jaw',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.2, max: 0.5 },
    costLevel: 'medium',
    costRange: { min: 400, max: 1200, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: '4-8 weeks for slimming effect',
    resultsDuration: '4-6 months',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 4-6 months (can extend with repeat treatments)',
    recoveryTime: 'None',
    downtime: 'None',
    painLevel: 'low',
    riskLevel: 'very_low',
    sideEffects: ['Temporary chewing weakness', 'Asymmetry', 'Smile changes'],
    contraindications: ['Pregnancy', 'Neuromuscular disorders'],
    targetMetrics: ['bigonial_width', 'jaw_width_ratio', 'fwhr'],
    targetIssues: ['wide_jaw', 'square_jaw', 'bruxism', 'teeth_grinding', 'TMJ'],
    genderSpecific: 'female',
    notes: [
      'Creates V-line face shape without surgery',
      'Also helps with teeth grinding and TMJ',
      'Requires higher units (25-50 per side)',
      'Effects become longer-lasting with repeat treatments',
      'Popular in East Asia for feminine face shape',
    ],
    sources: ['ASPS', 'Journal of Cosmetic Dermatology'],
  },
  {
    id: 'botox_lip_flip',
    name: 'Botox Lip Flip',
    category: 'minimally_invasive',
    description: 'Botulinum toxin to create appearance of fuller upper lip',
    howItWorks: 'Relaxes orbicularis oris muscle, allowing upper lip to roll outward',
    effectiveness: 6,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.05, max: 0.15 },
    costLevel: 'low',
    costRange: { min: 100, max: 300, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: '3-7 days',
    resultsDuration: '2-3 months',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 2-3 months',
    recoveryTime: 'None',
    downtime: 'None',
    painLevel: 'low',
    riskLevel: 'very_low',
    sideEffects: ['Difficulty drinking from straw', 'Asymmetric smile (temporary)'],
    contraindications: ['Pregnancy', 'Neuromuscular disorders'],
    targetMetrics: ['vermillion_show', 'upper_lip'],
    targetIssues: ['thin_upper_lip', 'gummy_smile', 'disappearing_lip_when_smiling'],
    notes: [
      'Subtle enhancement - not a replacement for filler',
      'Good for those who want minimal change',
      'Can combine with lip filler for best results',
      'Lower cost entry to lip enhancement',
    ],
    sources: ['ASPS'],
  },
  {
    id: 'botox_brow_lift',
    name: 'Botox Brow Lift',
    category: 'minimally_invasive',
    description: 'Strategic Botox to lift the eyebrows',
    howItWorks: 'Weakening brow depressors (orbicularis oculi, corrugator) allows frontalis to lift',
    effectiveness: 6,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.1, max: 0.2 },
    costLevel: 'low',
    costRange: { min: 200, max: 500, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: '7-14 days',
    resultsDuration: '3-4 months',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 3-4 months',
    recoveryTime: 'None',
    downtime: 'None',
    painLevel: 'low',
    riskLevel: 'very_low',
    sideEffects: ['Asymmetry', 'Spock brow', 'Heavy brow if overdone'],
    contraindications: ['Pregnancy', 'Very heavy brows'],
    targetMetrics: ['brow_position', 'canthal_tilt'],
    targetIssues: ['low_brows', 'hooded_eyes', 'tired_appearance'],
    notes: [
      'Lift is subtle (1-3mm)',
      'Requires skilled injector for symmetry',
      'Alternative to surgical brow lift',
      'Often combined with forehead Botox',
    ],
    sources: ['ASPS', 'Plastic and Reconstructive Surgery'],
  },

  // ============================================
  // SKIN TREATMENTS
  // ============================================
  {
    id: 'microneedling',
    name: 'Microneedling (Skin Pen)',
    category: 'non_surgical',
    description: 'Controlled micro-injuries to stimulate collagen production',
    howItWorks: 'Tiny needles create micro-channels, triggering wound healing and collagen remodeling',
    effectiveness: 7,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.1, max: 0.3 },
    costLevel: 'medium',
    costRange: { min: 200, max: 700, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: '4-6 weeks per session, 3-6 sessions for optimal results',
    resultsDuration: 'Long-lasting with maintenance',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 4-6 weeks for series, then 1-2x/year maintenance',
    recoveryTime: '2-3 days',
    downtime: '24-72 hours of redness',
    painLevel: 'moderate',
    riskLevel: 'low',
    sideEffects: ['Redness', 'Swelling', 'Dryness', 'Bruising (rare)'],
    contraindications: ['Active acne', 'Eczema', 'Keloid tendency', 'Blood thinners'],
    targetMetrics: ['skin_quality', 'overall_harmony'],
    targetIssues: ['acne_scars', 'fine_lines', 'enlarged_pores', 'uneven_texture', 'stretch_marks'],
    notes: [
      'Can be combined with PRP (vampire facial) for enhanced results',
      'Depth of needling varies by treatment area',
      'Home devices less effective than professional',
      'Avoid retinoids 5-7 days before and after',
    ],
    sources: ['Journal of Cutaneous and Aesthetic Surgery', 'Dermatologic Surgery'],
  },
  {
    id: 'prp_facial',
    name: 'PRP Facial (Platelet-Rich Plasma)',
    category: 'non_surgical',
    description: 'Your own growth factors injected or applied to stimulate rejuvenation',
    howItWorks: 'Blood is drawn, centrifuged to concentrate platelets, then applied/injected to skin',
    effectiveness: 6,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.1, max: 0.2 },
    costLevel: 'high',
    costRange: { min: 500, max: 1500, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: '4-8 weeks, optimal after series',
    resultsDuration: '12-18 months',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 12-18 months after initial series',
    recoveryTime: '1-3 days',
    downtime: '24-48 hours of redness',
    painLevel: 'moderate',
    riskLevel: 'very_low',
    sideEffects: ['Redness', 'Swelling', 'Bruising at blood draw site'],
    contraindications: ['Blood disorders', 'Active infection', 'Cancer'],
    targetMetrics: ['skin_quality', 'hair_density'],
    targetIssues: ['skin_aging', 'hair_loss', 'acne_scars', 'dark_circles'],
    notes: [
      'Uses your own cells - no allergy risk',
      'Often combined with microneedling',
      'Also used for hair restoration',
      'Quality depends on PRP preparation protocol',
    ],
    sources: ['Aesthetic Plastic Surgery', 'Journal of Cutaneous and Aesthetic Surgery'],
  },
  {
    id: 'chemical_peel',
    name: 'Chemical Peel (Medium Depth)',
    category: 'non_surgical',
    description: 'Controlled chemical exfoliation to resurface skin',
    howItWorks: 'Acid solution removes damaged outer layers, stimulating new skin growth',
    effectiveness: 7,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.1, max: 0.3 },
    costLevel: 'medium',
    costRange: { min: 150, max: 600, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: '1-2 weeks for peeling, final results 4-8 weeks',
    resultsDuration: 'Long-lasting with sun protection',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 3-6 months',
    recoveryTime: '5-14 days depending on depth',
    downtime: '3-7 days of peeling and redness',
    painLevel: 'moderate',
    riskLevel: 'low',
    sideEffects: ['Redness', 'Peeling', 'Sensitivity', 'PIH in darker skin types'],
    contraindications: ['Recent Accutane use', 'Active herpes', 'Darker skin (for deep peels)'],
    targetMetrics: ['skin_quality'],
    targetIssues: ['hyperpigmentation', 'acne_scars', 'fine_lines', 'sun_damage', 'uneven_tone'],
    notes: [
      'Glycolic, salicylic, TCA, and Jessner are common types',
      'Depth determines results and downtime',
      'Darker skin types need experienced provider (PIH risk)',
      'Strict sun protection required after',
    ],
    sources: ['ASPS', 'Journal of the American Academy of Dermatology'],
  },
  {
    id: 'laser_resurfacing',
    name: 'Fractional CO2 Laser Resurfacing',
    category: 'non_surgical',
    description: 'Laser treatment to dramatically improve skin texture and tightness',
    howItWorks: 'Laser creates microscopic columns of damage, triggering intense collagen remodeling',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.2, max: 0.5 },
    costLevel: 'very_high',
    costRange: { min: 1000, max: 5000, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: '3-6 months for collagen remodeling',
    resultsDuration: 'Long-lasting (years)',
    maintenanceRequired: false,
    recoveryTime: '1-2 weeks',
    downtime: '5-10 days of significant redness, peeling',
    painLevel: 'moderate',
    riskLevel: 'medium',
    sideEffects: ['Redness', 'Swelling', 'Peeling', 'PIH', 'Scarring (rare)', 'Infection'],
    contraindications: ['Darker skin types (high PIH risk)', 'Active acne', 'Recent tan'],
    targetMetrics: ['skin_quality', 'wrinkle_depth'],
    targetIssues: ['deep_wrinkles', 'acne_scars', 'sun_damage', 'skin_laxity'],
    notes: [
      'Gold standard for skin resurfacing',
      'Ablative CO2 most aggressive, fractional reduces downtime',
      'Not recommended for Fitzpatrick IV-VI',
      'Can be combined with other treatments for comprehensive rejuvenation',
    ],
    sources: ['ASPS', 'Dermatologic Surgery'],
  },
  {
    id: 'ipl',
    name: 'IPL (Intense Pulsed Light)',
    category: 'non_surgical',
    description: 'Broad spectrum light treatment for pigmentation and redness',
    howItWorks: 'Light targets melanin and hemoglobin to reduce brown spots and redness',
    effectiveness: 7,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.1, max: 0.2 },
    costLevel: 'medium',
    costRange: { min: 200, max: 600, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: '1-3 weeks per session, 3-6 sessions typical',
    resultsDuration: 'Long-lasting with sun protection',
    maintenanceRequired: true,
    maintenanceFrequency: '1-2x/year maintenance',
    recoveryTime: '1-3 days',
    downtime: 'Minimal - spots darken then flake off',
    painLevel: 'low',
    riskLevel: 'low',
    sideEffects: ['Temporary darkening of spots', 'Redness', 'Crusting'],
    contraindications: ['Tan skin', 'Darker skin types', 'Melasma (may worsen)'],
    targetMetrics: ['skin_quality', 'skin_tone'],
    targetIssues: ['sun_spots', 'redness', 'rosacea', 'broken_capillaries', 'freckles'],
    notes: [
      'Cannot be done on tanned skin',
      'Not safe for darker skin types',
      'Series of treatments needed for best results',
      'Good maintenance for aging skin',
    ],
    sources: ['Journal of Cosmetic Dermatology', 'ASPS'],
  },
  {
    id: 'rf_microneedling',
    name: 'RF Microneedling (Morpheus8/Potenza)',
    category: 'non_surgical',
    description: 'Combines microneedling with radiofrequency for deeper remodeling',
    howItWorks: 'Needles deliver RF energy to deeper skin layers, stimulating collagen and tightening',
    effectiveness: 8,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.2, max: 0.4 },
    costLevel: 'high',
    costRange: { min: 800, max: 2000, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: '4-8 weeks per session, optimal after 3 sessions',
    resultsDuration: '1-3 years',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 12-18 months after initial series',
    recoveryTime: '3-5 days',
    downtime: '3-5 days of redness and swelling',
    painLevel: 'moderate',
    riskLevel: 'low',
    sideEffects: ['Redness', 'Swelling', 'Crusting', 'Temporary grid pattern'],
    contraindications: ['Pacemaker', 'Active acne', 'Pregnancy'],
    targetMetrics: ['skin_quality', 'skin_laxity'],
    targetIssues: ['skin_laxity', 'acne_scars', 'wrinkles', 'large_pores', 'jowls'],
    notes: [
      'Safe for all skin types (unlike CO2 laser)',
      'Morpheus8 and Potenza are popular devices',
      'Can treat face and body',
      'Deeper penetration than regular microneedling',
    ],
    sources: ['Dermatologic Surgery', 'Journal of Cosmetic Dermatology'],
  },
  {
    id: 'ultrasound_lifting',
    name: 'Ultherapy (Ultrasound Lifting)',
    category: 'non_surgical',
    description: 'Focused ultrasound to lift and tighten skin',
    howItWorks: 'Ultrasound energy heats deep tissue layers, stimulating collagen and lifting',
    effectiveness: 6,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.1, max: 0.3 },
    costLevel: 'very_high',
    costRange: { min: 2000, max: 5000, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: '3-6 months for full effect',
    resultsDuration: '1-2 years',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 1-2 years',
    recoveryTime: 'None',
    downtime: 'None - some temporary redness',
    painLevel: 'high',
    riskLevel: 'low',
    sideEffects: ['Pain during treatment', 'Temporary redness', 'Swelling', 'Nerve tingling'],
    contraindications: ['Metal implants in area', 'Severe skin laxity'],
    targetMetrics: ['skin_laxity', 'jowls'],
    targetIssues: ['mild_laxity', 'jowls', 'brow_droop', 'neck_laxity'],
    notes: [
      'Only FDA-cleared device for lifting',
      'Results subtle - not a facelift replacement',
      'Very painful - numbing cream or medication recommended',
      'Best for mild to moderate laxity',
    ],
    sources: ['FDA', 'ASPS'],
  },

  // ============================================
  // THREAD TREATMENTS
  // ============================================
  {
    id: 'pdo_threads',
    name: 'PDO Thread Lift',
    category: 'minimally_invasive',
    description: 'Dissolvable threads inserted under skin for lifting and collagen stimulation',
    howItWorks: 'PDO threads inserted via needles provide mechanical lift and stimulate collagen as they dissolve',
    effectiveness: 6,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.1, max: 0.3 },
    costLevel: 'high',
    costRange: { min: 1500, max: 4500, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: 'Immediate lift, improving over 3 months',
    resultsDuration: '12-24 months',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 12-24 months',
    recoveryTime: '5-7 days',
    downtime: '3-7 days of swelling and bruising',
    painLevel: 'moderate',
    riskLevel: 'medium',
    sideEffects: ['Swelling', 'Bruising', 'Asymmetry', 'Thread migration', 'Puckering', 'Infection'],
    contraindications: ['Severe laxity', 'Bleeding disorders', 'Active infection'],
    targetMetrics: ['jowls', 'nasolabial_folds', 'brow_position'],
    targetIssues: ['mild_jowls', 'sagging_cheeks', 'nasolabial_folds', 'brow_ptosis'],
    notes: [
      'Bridge between injectables and facelift',
      'Results depend heavily on technique',
      'Barbed threads provide more lift than smooth',
      'Not suitable for significant laxity - consider surgery',
    ],
    sources: ['Aesthetic Plastic Surgery', 'Dermatologic Surgery'],
  },
  {
    id: 'cog_threads',
    name: 'Silhouette InstaLift (COG Threads)',
    category: 'minimally_invasive',
    description: 'Bidirectional cones provide stronger lift than PDO threads',
    howItWorks: 'PLLA/PLGA threads with cones provide mechanical lift and stimulate collagen',
    effectiveness: 7,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.2, max: 0.4 },
    costLevel: 'high',
    costRange: { min: 2000, max: 5000, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: 'Immediate lift, improving over 3-6 months',
    resultsDuration: '18-24 months',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 18-24 months',
    recoveryTime: '5-7 days',
    downtime: '3-7 days of swelling',
    painLevel: 'moderate',
    riskLevel: 'medium',
    sideEffects: ['Swelling', 'Bruising', 'Asymmetry', 'Dimpling', 'Thread visibility'],
    contraindications: ['Severe laxity', 'Very thin skin', 'Bleeding disorders'],
    targetMetrics: ['midface_lift', 'jowls'],
    targetIssues: ['midface_sagging', 'jowls', 'nasolabial_folds'],
    notes: [
      'FDA-approved for midface lifting',
      'Stronger lift than PDO threads',
      'PLLA cones continue stimulating collagen as they dissolve',
      'Requires experienced injector for natural results',
    ],
    sources: ['FDA', 'Plastic and Reconstructive Surgery'],
  },

  // ============================================
  // FAT REDUCTION
  // ============================================
  {
    id: 'kybella',
    name: 'Kybella (Deoxycholic Acid)',
    category: 'minimally_invasive',
    description: 'Injectable treatment to destroy submental fat (double chin)',
    howItWorks: 'Deoxycholic acid permanently destroys fat cells under the chin',
    effectiveness: 7,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.2, max: 0.4 },
    costLevel: 'high',
    costRange: { min: 1200, max: 2400, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: '4-6 weeks per session, 2-6 sessions needed',
    resultsDuration: 'Permanent (fat cells destroyed)',
    maintenanceRequired: false,
    recoveryTime: '1-2 weeks',
    downtime: '5-7 days of significant swelling',
    painLevel: 'moderate',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Bruising', 'Numbness', 'Hardness', 'Nerve injury (rare)'],
    contraindications: ['Infection in area', 'Difficulty swallowing', 'Pregnancy'],
    targetMetrics: ['submental_fullness', 'profile_harmony'],
    targetIssues: ['double_chin', 'submental_fat', 'undefined_jawline'],
    notes: [
      'FDA-approved for submental fat only',
      'Significant swelling for 1-2 weeks ("bullfrogs")',
      'Most need 2-4 sessions, 6 weeks apart',
      'Not effective for skin laxity - may need additional treatment',
    ],
    sources: ['FDA', 'ASPS'],
  },
  {
    id: 'coolsculpting_chin',
    name: 'CoolSculpting (Chin)',
    category: 'non_surgical',
    description: 'Cryolipolysis to freeze and eliminate submental fat',
    howItWorks: 'Controlled cooling crystallizes fat cells, which are then eliminated by the body',
    effectiveness: 6,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.1, max: 0.3 },
    costLevel: 'medium',
    costRange: { min: 700, max: 1500, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: '3-4 months',
    resultsDuration: 'Permanent (fat cells eliminated)',
    maintenanceRequired: false,
    recoveryTime: 'None',
    downtime: 'Minimal - temporary numbness',
    painLevel: 'low',
    riskLevel: 'very_low',
    sideEffects: ['Numbness', 'Redness', 'Bruising', 'PAH (paradoxical adipose hyperplasia, rare)'],
    contraindications: ['Cryoglobulinemia', 'Cold urticaria'],
    targetMetrics: ['submental_fullness'],
    targetIssues: ['double_chin', 'submental_fat'],
    notes: [
      'Less effective than Kybella for most patients',
      'PAH risk (fat grows larger instead of smaller) - rare but serious',
      'May need 2+ sessions',
      'More comfortable than Kybella',
    ],
    sources: ['ASPS', 'Dermatologic Surgery'],
  },
];

// Helper functions
export function getNonSurgicalByIssue(issue: string): Treatment[] {
  return NON_SURGICAL_TREATMENTS.filter(t =>
    t.targetIssues.some(i => i.toLowerCase().includes(issue.toLowerCase()))
  );
}

export function getNonSurgicalByMetric(metric: string): Treatment[] {
  return NON_SURGICAL_TREATMENTS.filter(t =>
    t.targetMetrics.some(m => m.toLowerCase().includes(metric.toLowerCase()))
  );
}

export function getNonSurgicalByCategory(category: 'minimally_invasive' | 'non_surgical'): Treatment[] {
  return NON_SURGICAL_TREATMENTS.filter(t => t.category === category);
}

export function getFillerTreatments(): Treatment[] {
  return NON_SURGICAL_TREATMENTS.filter(t => t.name.toLowerCase().includes('filler'));
}

export function getBotoxTreatments(): Treatment[] {
  return NON_SURGICAL_TREATMENTS.filter(t => t.name.toLowerCase().includes('botox'));
}

export function getSkinTreatments(): Treatment[] {
  return NON_SURGICAL_TREATMENTS.filter(t =>
    t.category === 'non_surgical' &&
    !t.name.toLowerCase().includes('cool')
  );
}

export function getLowRiskTreatments(): Treatment[] {
  return NON_SURGICAL_TREATMENTS.filter(t =>
    t.riskLevel === 'very_low' || t.riskLevel === 'low'
  );
}

export function getByDowntime(maxDays: number): Treatment[] {
  return NON_SURGICAL_TREATMENTS.filter(t => {
    const match = t.downtime.match(/(\d+)/);
    if (match) {
      return parseInt(match[1]) <= maxDays;
    }
    return t.downtime.toLowerCase().includes('none') || t.downtime.toLowerCase().includes('minimal');
  });
}
