/**
 * Softmaxxing Treatment Database
 * Non-invasive, reversible improvements for facial aesthetics
 */

import { Treatment } from './types';

export const SOFTMAXXING_TREATMENTS: Treatment[] = [
  // ============================================
  // SKINCARE
  // ============================================
  {
    id: 'sunscreen',
    name: 'Daily Sunscreen SPF 50+',
    category: 'softmaxxing',
    description: 'Broad-spectrum sun protection to prevent photoaging',
    howItWorks: 'Blocks UVA/UVB rays that cause 80% of facial aging, preventing collagen breakdown and hyperpigmentation',
    effectiveness: 10,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.1, max: 0.3 },
    costLevel: 'low',
    costRange: { min: 5, max: 30, currency: 'USD' },
    costFrequency: 'monthly',
    timelineToResults: 'Immediate protection, visible anti-aging benefits over months/years',
    resultsDuration: 'Ongoing with consistent use',
    maintenanceRequired: true,
    maintenanceFrequency: 'Daily application, reapply every 2 hours in sun',
    recoveryTime: 'None',
    downtime: 'None',
    painLevel: 'none',
    riskLevel: 'none',
    sideEffects: ['Rare: skin sensitivity to certain chemical filters'],
    contraindications: [],
    targetMetrics: ['skin_quality', 'overall_harmony'],
    targetIssues: ['premature_aging', 'hyperpigmentation', 'wrinkles', 'uneven_skin_tone'],
    notes: [
      'Single most effective anti-aging product',
      'Mineral sunscreens (zinc oxide) may be better for sensitive skin',
      'Apply as final step of skincare routine',
    ],
    sources: ['PMC6773941', 'Stanford Medicine 2025'],
  },
  {
    id: 'tretinoin',
    name: 'Tretinoin (Retin-A)',
    category: 'softmaxxing',
    description: 'Prescription retinoid for anti-aging, acne, and skin texture',
    howItWorks: 'Increases cell turnover, stimulates collagen production, unclogs pores, and reduces hyperpigmentation',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.2, max: 0.5 },
    costLevel: 'low',
    costRange: { min: 15, max: 50, currency: 'USD' },
    costFrequency: 'monthly',
    timelineToResults: '3-6 months for significant results',
    resultsDuration: 'Ongoing with continued use',
    maintenanceRequired: true,
    maintenanceFrequency: 'Nightly application',
    recoveryTime: 'None',
    downtime: '2-8 weeks adjustment period with possible purging',
    painLevel: 'low',
    riskLevel: 'low',
    sideEffects: ['Dryness', 'Peeling', 'Redness', 'Increased sun sensitivity', 'Initial purging'],
    contraindications: ['Pregnancy', 'Breastfeeding', 'Eczema flare-ups'],
    targetMetrics: ['skin_quality', 'overall_harmony'],
    targetIssues: ['acne', 'fine_lines', 'wrinkles', 'hyperpigmentation', 'rough_texture', 'enlarged_pores'],
    notes: [
      'Gold standard for anti-aging - decades of clinical research',
      'Start with 0.025% concentration, 1-2x per week',
      'Always use with sunscreen',
      'Buffer with moisturizer if irritation occurs',
    ],
    sources: ['Dermatology clinical trials', 'FDA approved'],
  },
  {
    id: 'vitamin_c_serum',
    name: 'Vitamin C Serum (L-Ascorbic Acid)',
    category: 'softmaxxing',
    description: 'Antioxidant serum for brightening and collagen support',
    howItWorks: 'Neutralizes free radicals, inhibits melanin production, and supports collagen synthesis',
    effectiveness: 7,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.1, max: 0.2 },
    costLevel: 'low',
    costRange: { min: 15, max: 180, currency: 'USD' },
    costFrequency: 'monthly',
    timelineToResults: '4-12 weeks',
    resultsDuration: 'Ongoing with continued use',
    maintenanceRequired: true,
    maintenanceFrequency: 'Daily morning application',
    recoveryTime: 'None',
    downtime: 'None',
    painLevel: 'none',
    riskLevel: 'very_low',
    sideEffects: ['Possible irritation on sensitive skin', 'Product oxidation (turns orange)'],
    contraindications: [],
    targetMetrics: ['skin_quality'],
    targetIssues: ['dull_skin', 'hyperpigmentation', 'uneven_skin_tone', 'sun_damage'],
    notes: [
      'Look for 10-20% concentration',
      'Best with Vitamin E and Ferulic Acid (CE Ferulic formula)',
      'Store in dark, cool place to prevent oxidation',
      'Apply before sunscreen in AM routine',
    ],
    sources: ['Dermatology research'],
  },

  // ============================================
  // EYEBROW ENHANCEMENT
  // ============================================
  {
    id: 'eyebrow_tinting',
    name: 'Eyebrow Tinting',
    category: 'softmaxxing',
    description: 'Semi-permanent dye to darken and define eyebrows',
    howItWorks: 'Vegetable or synthetic dye coats brow hairs, making them appear fuller and more defined',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.1, max: 0.3 },
    costLevel: 'low',
    costRange: { min: 15, max: 75, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: 'Immediate',
    resultsDuration: '3-6 weeks',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 3-6 weeks',
    recoveryTime: 'None',
    downtime: 'None (keep dry for 12 hours)',
    painLevel: 'none',
    riskLevel: 'very_low',
    sideEffects: ['Rare: allergic reaction to dye'],
    contraindications: ['Known dye allergies'],
    targetMetrics: ['eyebrow_position', 'facial_harmony'],
    targetIssues: ['light_eyebrows', 'sparse_eyebrows', 'grey_eyebrows', 'undefined_brows'],
    notes: [
      'Highest ROI softmax for immediate visible improvement',
      'DIY kits available for $10-20',
      'Avoid oil-based products for 24 hours after',
    ],
    sources: ['Cosmopolitan', 'Professional esthetician guides'],
  },
  {
    id: 'microblading',
    name: 'Microblading',
    category: 'softmaxxing',
    description: 'Semi-permanent cosmetic tattooing creating natural hair-like strokes',
    howItWorks: 'Handheld tool deposits pigment into the epidermis in fine strokes mimicking natural brow hairs',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.2, max: 0.5 },
    costLevel: 'medium',
    costRange: { min: 300, max: 2000, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: 'Immediate (final results after healing)',
    resultsDuration: '1-2 years',
    maintenanceRequired: true,
    maintenanceFrequency: 'Touch-up every 12-18 months',
    recoveryTime: '10-14 days',
    downtime: 'Avoid water, sun, retinoids on area for 10 days',
    painLevel: 'moderate',
    riskLevel: 'low',
    sideEffects: ['Swelling', 'Scabbing during healing', 'Color fading'],
    contraindications: ['Pregnancy', 'Blood thinners', 'Active acne in area', 'Keloid tendency'],
    targetMetrics: ['eyebrow_position', 'facial_harmony'],
    targetIssues: ['sparse_eyebrows', 'patchy_eyebrows', 'absent_eyebrows', 'asymmetric_brows'],
    notes: [
      '87% satisfaction rate on RealSelf',
      'Results depend heavily on artist skill',
      'Oily skin fades faster',
      'Two sessions typically required',
    ],
    sources: ['RealSelf', 'PMU Hub'],
  },

  // ============================================
  // EYELASH ENHANCEMENT
  // ============================================
  {
    id: 'latisse',
    name: 'Latisse (Bimatoprost)',
    category: 'softmaxxing',
    description: 'FDA-approved prescription treatment for eyelash growth',
    howItWorks: 'Prostaglandin analog that extends the anagen (growth) phase of lash hair cycle',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.1, max: 0.3 },
    costLevel: 'medium',
    costRange: { min: 35, max: 165, currency: 'USD' },
    costFrequency: 'monthly',
    timelineToResults: '4-16 weeks for full results',
    resultsDuration: 'Ongoing with continued use (reverses when stopped)',
    maintenanceRequired: true,
    maintenanceFrequency: 'Nightly application',
    recoveryTime: 'None',
    downtime: 'None',
    painLevel: 'none',
    riskLevel: 'low',
    sideEffects: ['Eye redness', 'Itching', 'Potential iris darkening (permanent)', 'Orbital fat loss with long-term use'],
    contraindications: ['Glaucoma medications', 'Eye infections'],
    targetMetrics: ['eye_area'],
    targetIssues: ['short_lashes', 'sparse_lashes', 'thin_lashes'],
    notes: [
      'Only FDA-approved lash growth treatment',
      'Results: 25% longer, 106% fuller, 18% darker lashes',
      'Generic bimatoprost available at lower cost',
      'Effects reverse within weeks of stopping',
    ],
    sources: ['FDA', 'Clinical trials'],
  },
  {
    id: 'eyelash_tinting',
    name: 'Eyelash Tinting',
    category: 'softmaxxing',
    description: 'Semi-permanent dye to darken lashes',
    howItWorks: 'Safe dye coats lash hairs, making them appear darker and more defined',
    effectiveness: 7,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.05, max: 0.15 },
    costLevel: 'low',
    costRange: { min: 20, max: 75, currency: 'USD' },
    costFrequency: 'per-session',
    timelineToResults: 'Immediate',
    resultsDuration: '3-6 weeks',
    maintenanceRequired: true,
    maintenanceFrequency: 'Every 3-6 weeks',
    recoveryTime: 'None',
    downtime: 'Avoid water for 24 hours',
    painLevel: 'none',
    riskLevel: 'very_low',
    sideEffects: ['Rare: eye irritation', 'Allergic reaction to dye'],
    contraindications: ['Eye infections', 'Dye allergies'],
    targetMetrics: ['eye_area'],
    targetIssues: ['light_lashes', 'blonde_lashes'],
    notes: [
      'Great for blonde or light-colored lashes',
      'Often combined with lash lift',
      'No mascara needed after',
    ],
    sources: ['Cosmopolitan', 'Professional guides'],
  },

  // ============================================
  // HAIR OPTIMIZATION
  // ============================================
  {
    id: 'minoxidil_topical',
    name: 'Minoxidil 5% (Rogaine/Kirkland)',
    category: 'softmaxxing',
    description: 'FDA-approved topical treatment for hair regrowth',
    howItWorks: 'Vasodilator that extends the anagen (growth) phase and stimulates hair follicles',
    effectiveness: 7,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.1, max: 0.4 },
    costLevel: 'low',
    costRange: { min: 7, max: 30, currency: 'USD' },
    costFrequency: 'monthly',
    timelineToResults: '3-6 months for visible results',
    resultsDuration: 'Ongoing with continued use (hair loss resumes if stopped)',
    maintenanceRequired: true,
    maintenanceFrequency: 'Twice daily application',
    recoveryTime: 'None',
    downtime: 'None',
    painLevel: 'none',
    riskLevel: 'low',
    sideEffects: ['Initial shedding (temporary)', 'Scalp irritation', 'Unwanted facial hair', 'Rare: heart palpitations'],
    contraindications: ['Heart conditions', 'Low blood pressure'],
    targetMetrics: ['hairline', 'overall_harmony'],
    targetIssues: ['hair_loss', 'thinning_hair', 'receding_hairline', 'male_pattern_baldness'],
    notes: [
      'Works for about 40% of users',
      'Kirkland brand is identical to Rogaine at lower cost',
      'Must continue indefinitely to maintain results',
      'Combining with microneedling increases effectiveness 4x',
    ],
    sources: ['FDA', 'Tressless community', 'Clinical trials'],
  },
  {
    id: 'finasteride',
    name: 'Finasteride 1mg (Propecia)',
    category: 'softmaxxing',
    description: 'Prescription DHT blocker to prevent and reverse hair loss',
    howItWorks: 'Inhibits 5-alpha reductase enzyme, reducing DHT by 66%, which slows/stops hair follicle miniaturization',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.2, max: 0.5 },
    costLevel: 'low',
    costRange: { min: 10, max: 30, currency: 'USD' },
    costFrequency: 'monthly',
    timelineToResults: '3-6 months to slow loss, 12-24 months for regrowth',
    resultsDuration: 'Ongoing with continued use',
    maintenanceRequired: true,
    maintenanceFrequency: 'Daily oral tablet',
    recoveryTime: 'None',
    downtime: 'None',
    painLevel: 'none',
    riskLevel: 'low',
    sideEffects: ['Decreased libido (2-5%)', 'Erectile dysfunction (2-5%)', 'Reduced ejaculate', 'Rare: depression'],
    contraindications: ['Women (especially pregnant)', 'Liver disease'],
    targetMetrics: ['hairline', 'overall_harmony'],
    targetIssues: ['hair_loss', 'male_pattern_baldness', 'receding_hairline'],
    genderSpecific: 'male',
    notes: [
      'Most effective for maintaining hair',
      '65% success rate for regrowth',
      'Nocebo effect: awareness of side effects increases reporting',
      'Topical finasteride may have fewer systemic effects',
      'Combined with minoxidil: 94% improvement rate',
    ],
    sources: ['FDA', 'Tressless research', 'Clinical trials'],
  },
  {
    id: 'microneedling_hair',
    name: 'Microneedling for Hair (Dermaroller)',
    category: 'softmaxxing',
    description: 'Creating micro-injuries to stimulate hair growth factors',
    howItWorks: 'Activates Wnt/beta-catenin signaling and VEGF, enhances minoxidil absorption by 4x',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.1, max: 0.3 },
    costLevel: 'low',
    costRange: { min: 10, max: 300, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '3-6 months',
    resultsDuration: 'Ongoing with continued treatment',
    maintenanceRequired: true,
    maintenanceFrequency: '1-2x per week',
    recoveryTime: '24-48 hours',
    downtime: 'Scalp redness for 1-2 days',
    painLevel: 'moderate',
    riskLevel: 'low',
    sideEffects: ['Scalp redness', 'Temporary irritation', 'Infection risk if not sanitized'],
    contraindications: ['Active scalp infections', 'Blood thinners', 'Keloid tendency'],
    targetMetrics: ['hairline', 'overall_harmony'],
    targetIssues: ['hair_loss', 'thinning_hair'],
    notes: [
      '2024 meta-analysis: 82% with microneedling + minoxidil showed >50% improvement',
      'vs only 4.5% with minoxidil alone',
      'Optimal needle depth: 0.5-1.5mm',
      'Wait 24 hours before applying minoxidil after needling',
    ],
    sources: ['Wiley Journal 2024', 'PMC3746236'],
  },
  {
    id: 'minoxidil_beard',
    name: 'Minoxidil for Beard Growth',
    category: 'softmaxxing',
    description: 'Off-label use of minoxidil to stimulate facial hair growth',
    howItWorks: 'Same vasodilation mechanism as scalp - extends anagen phase of facial hair follicles',
    effectiveness: 7,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.1, max: 0.4 },
    costLevel: 'low',
    costRange: { min: 7, max: 25, currency: 'USD' },
    costFrequency: 'monthly',
    timelineToResults: '6-12 months for significant results',
    resultsDuration: 'Permanent once hairs become terminal',
    maintenanceRequired: true,
    maintenanceFrequency: 'Twice daily for 12-16 months, then can stop',
    recoveryTime: 'None',
    downtime: 'None',
    painLevel: 'none',
    riskLevel: 'low',
    sideEffects: ['Dry facial skin', 'Unwanted hair growth near application', 'Initial shedding at month 3'],
    contraindications: ['Heart conditions'],
    targetMetrics: ['facial_hair', 'lower_third'],
    targetIssues: ['patchy_beard', 'thin_beard', 'no_beard'],
    genderSpecific: 'male',
    notes: [
      'r/minoxbeards community: 76,000+ members with documented results',
      'Vellus hairs appear at 1-2 months, terminal hairs by 12-16 months',
      'Results may become permanent after 12-16 months',
      'Use 5% topical, twice daily',
    ],
    sources: ['PMC10894539', 'r/minoxbeards'],
  },

  // ============================================
  // LEANMAXXING / LIFESTYLE
  // ============================================
  {
    id: 'leanmaxxing',
    name: 'Leanmaxxing (Body Fat Reduction)',
    category: 'lifestyle',
    description: 'Reducing body fat percentage to optimize facial definition',
    howItWorks: 'Lower subcutaneous facial fat reveals underlying bone structure, jawline, and cheekbones',
    effectiveness: 9,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.5, max: 1.5 },
    costLevel: 'free',
    costRange: { min: 0, max: 0, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '2-4 months to reach target body fat',
    resultsDuration: 'Ongoing with maintained body composition',
    maintenanceRequired: true,
    maintenanceFrequency: 'Ongoing diet and exercise',
    recoveryTime: 'None',
    downtime: 'None',
    painLevel: 'none',
    riskLevel: 'very_low',
    sideEffects: ['Temporary fatigue during deficit', 'Possible muscle loss if protein too low'],
    contraindications: ['Eating disorders', 'Underweight individuals'],
    targetMetrics: ['gonial_angle', 'jawline', 'cheekbone_projection', 'overall_harmony'],
    targetIssues: ['undefined_jawline', 'round_face', 'double_chin', 'lack_of_cheekbone_definition'],
    notes: [
      'Optimal male body fat: 10-15% (peak attractiveness at 12%)',
      'Optimal female body fat: 17-22%',
      'Most impactful free lifestyle change for facial aesthetics',
      '500 calorie deficit = ~1 lb/week fat loss',
      'High protein (1g/lb) preserves muscle during cut',
    ],
    sources: ['Frontiers Psychology 2018', 'PMC6308207'],
  },
  {
    id: 'sleep_optimization',
    name: 'Sleep Optimization (7-9 Hours)',
    category: 'lifestyle',
    description: 'Consistent quality sleep for skin health and facial appearance',
    howItWorks: 'Deep sleep enables cellular repair, collagen production, and reduces cortisol-induced inflammation',
    effectiveness: 8,
    evidenceLevel: 'strong',
    pslImprovement: { min: 0.1, max: 0.3 },
    costLevel: 'free',
    costRange: { min: 0, max: 0, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: 'Immediate reduction in puffiness, long-term skin quality improvement',
    resultsDuration: 'Ongoing with maintained sleep habits',
    maintenanceRequired: true,
    maintenanceFrequency: 'Nightly',
    recoveryTime: 'None',
    downtime: 'None',
    painLevel: 'none',
    riskLevel: 'none',
    sideEffects: [],
    contraindications: [],
    targetMetrics: ['skin_quality', 'eye_area', 'overall_harmony'],
    targetIssues: ['dark_circles', 'puffy_eyes', 'dull_skin', 'premature_aging'],
    notes: [
      'Poor sleepers score 4.4 vs 2.2 on skin aging scale',
      '2 nights of 3-hour sleep causes visible skin degradation',
      'Sleep deprivation causes: hanging eyelids, red eyes, pale skin, more wrinkles',
      'Sleeping on back prevents facial compression wrinkles',
    ],
    sources: ['ScienceDaily 2013', 'AASM Sleep Study', 'ScienceDirect 2021'],
  },
  {
    id: 'posture_correction',
    name: 'Posture Correction (Chin Tucks)',
    category: 'lifestyle',
    description: 'Exercises to correct forward head posture and reduce double chin appearance',
    howItWorks: 'Strengthens deep neck flexors, retracts head to proper position, improves jaw-neck angle',
    effectiveness: 6,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.1, max: 0.3 },
    costLevel: 'free',
    costRange: { min: 0, max: 0, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '4-8 weeks for visible improvement',
    resultsDuration: 'Ongoing with maintained posture',
    maintenanceRequired: true,
    maintenanceFrequency: 'Daily exercises (5-7 sessions of 10 reps)',
    recoveryTime: 'None',
    downtime: 'None',
    painLevel: 'none',
    riskLevel: 'none',
    sideEffects: ['Initial muscle soreness'],
    contraindications: ['Neck injuries without medical clearance'],
    targetMetrics: ['submental_cervical_angle', 'profile_harmony'],
    targetIssues: ['forward_head_posture', 'double_chin_appearance', 'poor_neck_jaw_angle'],
    notes: [
      'Every inch of forward head = 10 lbs extra neck strain',
      'Chin tucks: Pull chin back creating double chin, hold 5 seconds, 10 reps',
      'Wall angels and shoulder blade squeezes complement chin tucks',
      'Long-term FHP can cause permanent cervical changes',
    ],
    sources: ['NASM', 'Healthline', 'PubMed 35172275'],
  },
  {
    id: 'mewing',
    name: 'Mewing (Proper Tongue Posture)',
    category: 'lifestyle',
    description: 'Resting tongue against palate for potential facial development',
    howItWorks: 'Tongue pressure on palate may influence craniofacial development in youth; improves breathing/posture in adults',
    effectiveness: 3,
    evidenceLevel: 'weak',
    pslImprovement: { min: 0, max: 0.2 },
    costLevel: 'free',
    costRange: { min: 0, max: 0, currency: 'USD' },
    costFrequency: 'one-time',
    timelineToResults: '6-24 months (children), soft tissue only (adults 25+)',
    resultsDuration: 'Ongoing with maintained posture',
    maintenanceRequired: true,
    maintenanceFrequency: '24/7 tongue posture',
    recoveryTime: 'None',
    downtime: 'None',
    painLevel: 'none',
    riskLevel: 'very_low',
    sideEffects: ['TMJ discomfort if overdone', 'Initial jaw fatigue'],
    contraindications: ['TMJ disorders'],
    targetMetrics: ['facial_width', 'jawline'],
    targetIssues: ['recessed_maxilla', 'narrow_palate', 'mouth_breathing'],
    ageRestrictions: { max: 25 },
    notes: [
      'Most effective ages 5-10 (growing bones)',
      'Adults 25+: NO bone changes, soft tissue only',
      'No peer-reviewed studies proving adult bone remodeling',
      'May improve breathing and reduce double chin appearance',
      'NG technique: Say "king" - that tongue position is correct',
    ],
    sources: ['WebMD', 'Mewing.coach', 'Orthotropics critique'],
  },
  {
    id: 'debloating',
    name: 'Facial Debloating (Sodium/Potassium Balance)',
    category: 'lifestyle',
    description: 'Reducing water retention through electrolyte management',
    howItWorks: 'Potassium counteracts sodium-induced water retention, reducing facial puffiness',
    effectiveness: 7,
    evidenceLevel: 'moderate',
    pslImprovement: { min: 0.1, max: 0.3 },
    costLevel: 'free',
    costRange: { min: 0, max: 20, currency: 'USD' },
    costFrequency: 'monthly',
    timelineToResults: '2-5 days',
    resultsDuration: 'Ongoing with maintained diet',
    maintenanceRequired: true,
    maintenanceFrequency: 'Daily dietary choices',
    recoveryTime: 'None',
    downtime: 'None',
    painLevel: 'none',
    riskLevel: 'very_low',
    sideEffects: [],
    contraindications: ['Kidney disease (consult doctor for potassium)'],
    targetMetrics: ['jawline', 'cheekbone_projection'],
    targetIssues: ['puffy_face', 'water_retention', 'undefined_jawline'],
    notes: [
      'Target: 2,500-3,400mg potassium daily from whole foods',
      'Reduce sodium intake',
      'Drink 3-4L water daily (counterintuitively prevents retention)',
      'Best potassium sources: potatoes, bananas, avocados, spinach',
      'Alcohol and excess carbs increase facial bloat',
    ],
    sources: ['Healthline', 'Mewinghub'],
  },
];

export function getSoftmaxxingByIssue(issue: string): Treatment[] {
  return SOFTMAXXING_TREATMENTS.filter(t =>
    t.targetIssues.some(i => i.toLowerCase().includes(issue.toLowerCase()))
  );
}

export function getSoftmaxxingByMetric(metric: string): Treatment[] {
  return SOFTMAXXING_TREATMENTS.filter(t =>
    t.targetMetrics.some(m => m.toLowerCase().includes(metric.toLowerCase()))
  );
}

export function getSoftmaxxingByCategory(category: 'lifestyle' | 'softmaxxing'): Treatment[] {
  return SOFTMAXXING_TREATMENTS.filter(t => t.category === category);
}

export function getSoftmaxxingByEffectiveness(minEffectiveness: number = 7): Treatment[] {
  return SOFTMAXXING_TREATMENTS
    .filter(t => t.effectiveness >= minEffectiveness)
    .sort((a, b) => b.effectiveness - a.effectiveness);
}
