/**
 * Supplements Database
 * Evidence-based supplements for facial aesthetics and anti-aging
 */

import { Supplement } from './types';

export const SUPPLEMENTS: Supplement[] = [
  // ============================================
  // SKIN SUPPLEMENTS
  // ============================================
  {
    id: 'collagen_peptides',
    name: 'Collagen Peptides (Hydrolyzed)',
    category: 'skin',
    description: 'Hydrolyzed collagen powder for skin elasticity and hydration',
    dosage: '5-15g',
    frequency: 'Daily',
    timing: 'Any time, with or without food',
    effectiveness: 7,
    evidenceLevel: 'moderate',
    costPerMonth: { min: 15, max: 40 },
    timelineToResults: '4-12 weeks',
    riskLevel: 'very_low',
    sideEffects: ['Mild digestive upset', 'Bad taste (some products)'],
    interactions: [],
    contraindications: ['Fish/shellfish allergy (marine collagen)'],
    targetBenefits: ['skin_elasticity', 'wrinkle_reduction', 'skin_hydration', 'nail_strength'],
    requiresPrescription: false,
    notes: [
      'Type I and III collagen most beneficial for skin',
      '2019 meta-analysis: significant improvement in skin elasticity and hydration',
      'Vitamin C enhances collagen synthesis - take together',
      'Marine collagen has better bioavailability than bovine',
    ],
    sources: ['PMC6835901', 'Journal of Cosmetic Dermatology 2019'],
  },
  {
    id: 'vitamin_c_oral',
    name: 'Vitamin C (Ascorbic Acid)',
    category: 'skin',
    description: 'Essential antioxidant for collagen synthesis and skin health',
    dosage: '500-1000mg',
    frequency: 'Daily',
    timing: 'With meals',
    effectiveness: 7,
    evidenceLevel: 'strong',
    costPerMonth: { min: 5, max: 20 },
    timelineToResults: '4-8 weeks',
    riskLevel: 'very_low',
    sideEffects: ['GI upset at high doses', 'Kidney stones (rare, high doses)'],
    interactions: ['May increase iron absorption'],
    contraindications: ['History of kidney stones (high doses)'],
    targetBenefits: ['collagen_synthesis', 'antioxidant', 'wound_healing', 'sun_damage_protection'],
    requiresPrescription: false,
    notes: [
      'Required co-factor for collagen synthesis',
      'Liposomal vitamin C has better absorption',
      'Divide doses throughout day for optimal absorption',
      'Enhances effectiveness of topical vitamin C',
    ],
    sources: ['NIH Office of Dietary Supplements', 'Nutrients 2017'],
  },
  {
    id: 'vitamin_e',
    name: 'Vitamin E (d-Alpha Tocopherol)',
    category: 'skin',
    description: 'Fat-soluble antioxidant for skin protection',
    dosage: '400 IU',
    frequency: 'Daily',
    timing: 'With fatty meal',
    effectiveness: 6,
    evidenceLevel: 'moderate',
    costPerMonth: { min: 5, max: 15 },
    timelineToResults: '4-8 weeks',
    riskLevel: 'low',
    sideEffects: ['Increased bleeding risk at high doses'],
    interactions: ['Blood thinners', 'Statins'],
    contraindications: ['Bleeding disorders', 'Upcoming surgery'],
    targetBenefits: ['skin_protection', 'antioxidant', 'wound_healing'],
    requiresPrescription: false,
    notes: [
      'Natural form (d-) is more bioavailable than synthetic (dl-)',
      'Works synergistically with vitamin C',
      'May help with UV damage protection',
    ],
    sources: ['NIH Office of Dietary Supplements'],
  },
  {
    id: 'hyaluronic_acid_oral',
    name: 'Hyaluronic Acid (Oral)',
    category: 'skin',
    description: 'Oral supplement for skin hydration and joint health',
    dosage: '120-240mg',
    frequency: 'Daily',
    timing: 'With food',
    effectiveness: 5,
    evidenceLevel: 'weak',
    costPerMonth: { min: 10, max: 30 },
    timelineToResults: '4-12 weeks',
    riskLevel: 'very_low',
    sideEffects: ['Rare: mild GI upset'],
    interactions: [],
    contraindications: [],
    targetBenefits: ['skin_hydration', 'joint_health', 'skin_elasticity'],
    requiresPrescription: false,
    notes: [
      'Limited evidence for oral bioavailability',
      'May work best with collagen supplementation',
      'Lower molecular weight forms may absorb better',
    ],
    sources: ['Nutrition Journal 2014'],
  },
  {
    id: 'astaxanthin',
    name: 'Astaxanthin',
    category: 'skin',
    description: 'Powerful carotenoid antioxidant from algae',
    dosage: '4-12mg',
    frequency: 'Daily',
    timing: 'With fatty meal',
    effectiveness: 7,
    evidenceLevel: 'moderate',
    costPerMonth: { min: 15, max: 40 },
    timelineToResults: '4-8 weeks',
    riskLevel: 'very_low',
    sideEffects: ['Orange/red discoloration of stool'],
    interactions: [],
    contraindications: [],
    targetBenefits: ['UV_protection', 'wrinkle_reduction', 'skin_elasticity', 'antioxidant'],
    requiresPrescription: false,
    notes: [
      '6000x more potent than vitamin C as antioxidant',
      'Provides internal sun protection (does not replace sunscreen)',
      'May improve skin moisture and elasticity',
      'Natural source: Haematococcus pluvialis algae',
    ],
    sources: ['PMC3917265', 'Clinical interventions in aging 2012'],
  },
  {
    id: 'niacinamide_oral',
    name: 'Niacinamide (Vitamin B3)',
    category: 'skin',
    description: 'B vitamin for skin barrier function and sebum control',
    dosage: '500-1000mg',
    frequency: 'Daily',
    timing: 'With food',
    effectiveness: 6,
    evidenceLevel: 'moderate',
    costPerMonth: { min: 5, max: 15 },
    timelineToResults: '4-8 weeks',
    riskLevel: 'very_low',
    sideEffects: ['Flushing (less than niacin)', 'GI upset'],
    interactions: [],
    contraindications: [],
    targetBenefits: ['sebum_control', 'skin_barrier', 'hyperpigmentation', 'anti_inflammation'],
    requiresPrescription: false,
    notes: [
      'Different from niacin - does not cause flushing',
      'May help with acne and oily skin',
      'Supports NAD+ production for cellular health',
    ],
    sources: ['Dermatologic Therapy 2005', 'NIH'],
  },

  // ============================================
  // HAIR SUPPLEMENTS
  // ============================================
  {
    id: 'biotin',
    name: 'Biotin (Vitamin B7)',
    category: 'hair',
    description: 'B vitamin commonly supplemented for hair and nail health',
    dosage: '2500-5000mcg',
    frequency: 'Daily',
    timing: 'With food',
    effectiveness: 4,
    evidenceLevel: 'weak',
    costPerMonth: { min: 5, max: 15 },
    timelineToResults: '3-6 months',
    riskLevel: 'very_low',
    sideEffects: ['May interfere with lab tests (thyroid, cardiac)'],
    interactions: ['Interferes with certain lab tests'],
    contraindications: ['Stop 72 hours before blood tests'],
    targetBenefits: ['hair_growth', 'nail_strength'],
    requiresPrescription: false,
    notes: [
      'Only beneficial if you are deficient (rare)',
      'No good evidence for non-deficient individuals',
      'Very high doses can skew lab results',
      'Most people get enough from diet',
    ],
    sources: ['NIH Office of Dietary Supplements', 'JAAD 2017'],
  },
  {
    id: 'iron',
    name: 'Iron (Ferrous Sulfate/Bisglycinate)',
    category: 'hair',
    description: 'Essential mineral for hair growth - only if deficient',
    dosage: '18-65mg elemental iron',
    frequency: 'Daily or every other day',
    timing: 'On empty stomach with vitamin C',
    effectiveness: 8,
    evidenceLevel: 'strong',
    costPerMonth: { min: 5, max: 15 },
    timelineToResults: '3-6 months',
    riskLevel: 'low',
    sideEffects: ['Constipation', 'Nausea', 'Stomach upset', 'Dark stool'],
    interactions: ['Thyroid medications', 'Antacids', 'Tetracyclines'],
    contraindications: ['Hemochromatosis', 'Already adequate iron levels'],
    targetBenefits: ['hair_growth', 'energy', 'prevent_hair_loss'],
    requiresPrescription: false,
    notes: [
      'Only supplement if ferritin is low (<70ng/mL for hair)',
      'Iron bisglycinate causes less GI upset',
      'Take with vitamin C to enhance absorption',
      'Avoid taking with dairy, coffee, tea',
      'Get blood test before supplementing',
    ],
    sources: ['JAAD 2013', 'Journal of Korean Medical Science'],
  },
  {
    id: 'vitamin_d3',
    name: 'Vitamin D3 (Cholecalciferol)',
    category: 'hair',
    description: 'Essential vitamin for hair follicle cycling and overall health',
    dosage: '2000-5000 IU',
    frequency: 'Daily',
    timing: 'With fatty meal',
    effectiveness: 7,
    evidenceLevel: 'moderate',
    costPerMonth: { min: 5, max: 15 },
    timelineToResults: '3-6 months',
    riskLevel: 'very_low',
    sideEffects: ['Toxicity only at very high doses (>10,000 IU daily long-term)'],
    interactions: ['Thiazide diuretics'],
    contraindications: ['Hypercalcemia', 'Kidney disease'],
    targetBenefits: ['hair_growth', 'immune_function', 'bone_health', 'mood'],
    requiresPrescription: false,
    notes: [
      'Deficiency linked to hair loss (alopecia)',
      'Test levels before supplementing heavily',
      'Optimal blood level: 40-60 ng/mL',
      'K2 often paired with D3 for calcium metabolism',
    ],
    sources: ['International Journal of Trichology 2013', 'Dermatology Practical & Conceptual'],
  },
  {
    id: 'zinc',
    name: 'Zinc (Picolinate/Bisglycinate)',
    category: 'hair',
    description: 'Essential mineral for hair protein synthesis and immune function',
    dosage: '15-30mg',
    frequency: 'Daily',
    timing: 'With food (not with iron)',
    effectiveness: 6,
    evidenceLevel: 'moderate',
    costPerMonth: { min: 5, max: 15 },
    timelineToResults: '3-6 months',
    riskLevel: 'low',
    sideEffects: ['Nausea if taken on empty stomach', 'Copper depletion at high doses'],
    interactions: ['Antibiotics', 'Iron (take separately)'],
    contraindications: [],
    targetBenefits: ['hair_growth', 'immune_function', 'skin_healing', 'acne'],
    requiresPrescription: false,
    notes: [
      'Deficiency can cause hair loss',
      'Long-term high doses deplete copper - consider copper supplement',
      'Zinc picolinate and bisglycinate better absorbed',
      'Take separately from iron supplements (2+ hours apart)',
    ],
    sources: ['Dermatology Research and Practice 2014'],
  },
  {
    id: 'saw_palmetto',
    name: 'Saw Palmetto Extract',
    category: 'hair',
    description: 'Natural DHT blocker for hair loss prevention',
    dosage: '320mg',
    frequency: 'Daily',
    timing: 'With food',
    effectiveness: 5,
    evidenceLevel: 'weak',
    costPerMonth: { min: 10, max: 25 },
    timelineToResults: '6-12 months',
    riskLevel: 'low',
    sideEffects: ['GI upset', 'Headache'],
    interactions: ['Blood thinners', 'Hormonal contraceptives'],
    contraindications: ['Hormone-sensitive conditions'],
    targetBenefits: ['DHT_blocking', 'hair_loss_prevention'],
    requiresPrescription: false,
    notes: [
      'Weaker DHT inhibition than finasteride',
      'May help in conjunction with finasteride/minoxidil',
      'Some studies show modest improvement in hair count',
      'Popular natural alternative to prescription options',
    ],
    sources: ['Journal of Alternative and Complementary Medicine 2002', 'Cochrane Review'],
  },

  // ============================================
  // ANTI-AGING SUPPLEMENTS
  // ============================================
  {
    id: 'omega_3',
    name: 'Omega-3 Fish Oil (EPA/DHA)',
    category: 'anti-aging',
    description: 'Essential fatty acids for skin health and systemic inflammation',
    dosage: '2-3g combined EPA/DHA',
    frequency: 'Daily',
    timing: 'With fatty meal',
    effectiveness: 7,
    evidenceLevel: 'strong',
    costPerMonth: { min: 15, max: 40 },
    timelineToResults: '4-12 weeks',
    riskLevel: 'very_low',
    sideEffects: ['Fishy burps', 'Mild GI upset'],
    interactions: ['Blood thinners'],
    contraindications: ['Fish allergy', 'Upcoming surgery'],
    targetBenefits: ['anti_inflammation', 'skin_barrier', 'brain_health', 'heart_health'],
    requiresPrescription: false,
    notes: [
      'Look for products tested for heavy metals/PCBs',
      'EPA more anti-inflammatory, DHA more for brain',
      'Algae-based omega-3 available for vegetarians',
      'May help with dry skin and inflammatory skin conditions',
    ],
    sources: ['Journal of the American Academy of Dermatology', 'American Heart Association'],
  },
  {
    id: 'coq10',
    name: 'CoQ10 (Ubiquinol)',
    category: 'anti-aging',
    description: 'Cellular energy and antioxidant for aging skin',
    dosage: '100-200mg',
    frequency: 'Daily',
    timing: 'With fatty meal',
    effectiveness: 6,
    evidenceLevel: 'moderate',
    costPerMonth: { min: 15, max: 40 },
    timelineToResults: '4-12 weeks',
    riskLevel: 'very_low',
    sideEffects: ['Rare: insomnia, digestive upset'],
    interactions: ['Blood thinners', 'Blood pressure medications'],
    contraindications: [],
    targetBenefits: ['cellular_energy', 'antioxidant', 'wrinkle_reduction'],
    requiresPrescription: false,
    notes: [
      'Ubiquinol is active form, better absorbed than ubiquinone',
      'CoQ10 levels decline with age',
      'May help with energy and skin quality',
      'Statin drugs deplete CoQ10 - consider if on statins',
    ],
    sources: ['Biofactors 2017', 'Clinical Interventions in Aging'],
  },
  {
    id: 'nad_precursor',
    name: 'NMN or NR (NAD+ Precursor)',
    category: 'anti-aging',
    description: 'Nicotinamide precursor for cellular energy and longevity',
    dosage: '250-500mg',
    frequency: 'Daily',
    timing: 'Morning, with or without food',
    effectiveness: 5,
    evidenceLevel: 'weak',
    costPerMonth: { min: 40, max: 100 },
    timelineToResults: '4-12 weeks (subjective energy), long-term unknown',
    riskLevel: 'low',
    sideEffects: ['Mild nausea', 'Insomnia if taken late'],
    interactions: [],
    contraindications: [],
    targetBenefits: ['cellular_energy', 'longevity', 'DNA_repair'],
    requiresPrescription: false,
    notes: [
      'Popular longevity supplement but human evidence limited',
      'NMN and NR both raise NAD+ levels',
      'Animal studies promising, human studies ongoing',
      'David Sinclair research has popularized these',
    ],
    sources: ['Cell Metabolism 2018', 'Nature Communications'],
  },
  {
    id: 'resveratrol',
    name: 'Resveratrol',
    category: 'anti-aging',
    description: 'Polyphenol antioxidant from grapes with potential longevity benefits',
    dosage: '250-500mg',
    frequency: 'Daily',
    timing: 'With fatty meal',
    effectiveness: 4,
    evidenceLevel: 'weak',
    costPerMonth: { min: 15, max: 40 },
    timelineToResults: 'Long-term (months-years)',
    riskLevel: 'low',
    sideEffects: ['GI upset at high doses'],
    interactions: ['Blood thinners', 'Medications metabolized by liver'],
    contraindications: ['Hormone-sensitive conditions'],
    targetBenefits: ['antioxidant', 'longevity', 'cardiovascular'],
    requiresPrescription: false,
    notes: [
      'Trans-resveratrol is the active form',
      'Poor bioavailability - look for enhanced formulations',
      'Animal studies promising but human evidence mixed',
      'Often paired with NMN/NR in longevity protocols',
    ],
    sources: ['Nutrients 2020', 'Annals of the New York Academy of Sciences'],
  },

  // ============================================
  // HORMONAL SUPPORT
  // ============================================
  {
    id: 'ashwagandha',
    name: 'Ashwagandha (KSM-66)',
    category: 'hormonal',
    description: 'Adaptogen for stress reduction and testosterone support',
    dosage: '300-600mg',
    frequency: 'Daily',
    timing: 'Morning or evening with food',
    effectiveness: 7,
    evidenceLevel: 'moderate',
    costPerMonth: { min: 10, max: 30 },
    timelineToResults: '4-8 weeks',
    riskLevel: 'low',
    sideEffects: ['Drowsiness', 'GI upset', 'Thyroid changes'],
    interactions: ['Thyroid medications', 'Sedatives'],
    contraindications: ['Thyroid disorders (consult doctor)', 'Autoimmune conditions'],
    targetBenefits: ['stress_reduction', 'testosterone', 'sleep', 'anxiety'],
    requiresPrescription: false,
    notes: [
      'KSM-66 is the most studied extract',
      'May modestly increase testosterone in men',
      'Adaptogen - helps body manage stress',
      'Can affect thyroid - monitor if you have thyroid issues',
    ],
    sources: ['Journal of the International Society of Sports Nutrition 2015', 'Cureus 2019'],
  },
  {
    id: 'tongkat_ali',
    name: 'Tongkat Ali (Eurycoma Longifolia)',
    category: 'hormonal',
    description: 'Malaysian herb for testosterone and energy support',
    dosage: '200-400mg',
    frequency: 'Daily',
    timing: 'Morning with food',
    effectiveness: 6,
    evidenceLevel: 'moderate',
    costPerMonth: { min: 20, max: 50 },
    timelineToResults: '4-12 weeks',
    riskLevel: 'low',
    sideEffects: ['Restlessness', 'Insomnia', 'Increased aggression'],
    interactions: [],
    contraindications: ['Hormone-sensitive cancers'],
    targetBenefits: ['testosterone', 'energy', 'libido', 'stress_reduction'],
    requiresPrescription: false,
    notes: [
      'Look for standardized extracts (2% eurycomanone)',
      'May help with cortisol reduction',
      'Studies show modest testosterone increase in men with low-normal T',
      'Cycle usage: 5 days on, 2 days off',
    ],
    sources: ['Andrologia 2012', 'Journal of the International Society of Sports Nutrition 2013'],
  },
  {
    id: 'dim',
    name: 'DIM (Diindolylmethane)',
    category: 'hormonal',
    description: 'Cruciferous vegetable extract for estrogen metabolism',
    dosage: '100-200mg',
    frequency: 'Daily',
    timing: 'With food',
    effectiveness: 5,
    evidenceLevel: 'weak',
    costPerMonth: { min: 15, max: 30 },
    timelineToResults: '4-8 weeks',
    riskLevel: 'low',
    sideEffects: ['GI upset', 'Headache', 'Dark urine'],
    interactions: ['Medications metabolized by CYP enzymes'],
    contraindications: ['Hormone-sensitive conditions (consult doctor)'],
    targetBenefits: ['estrogen_balance', 'acne', 'hormonal_balance'],
    requiresPrescription: false,
    notes: [
      'Promotes favorable estrogen metabolism',
      'May help with hormonal acne',
      'Found naturally in broccoli, cabbage, etc.',
      'Some use for post-cycle therapy',
    ],
    sources: ['Nutrition Reviews 2016'],
  },

  // ============================================
  // BONE & COLLAGEN SUPPORT
  // ============================================
  {
    id: 'vitamin_k2',
    name: 'Vitamin K2 (MK-7)',
    category: 'bone',
    description: 'Fat-soluble vitamin for calcium metabolism and bone health',
    dosage: '100-200mcg',
    frequency: 'Daily',
    timing: 'With fatty meal, paired with D3',
    effectiveness: 6,
    evidenceLevel: 'moderate',
    costPerMonth: { min: 10, max: 25 },
    timelineToResults: 'Long-term (months)',
    riskLevel: 'very_low',
    sideEffects: [],
    interactions: ['Blood thinners (warfarin)'],
    contraindications: ['On warfarin (consult doctor)'],
    targetBenefits: ['bone_health', 'calcium_metabolism', 'cardiovascular'],
    requiresPrescription: false,
    notes: [
      'Directs calcium to bones, away from arteries',
      'MK-7 form has longer half-life than MK-4',
      'Important when supplementing vitamin D3',
      'Found in natto, fermented foods, some cheeses',
    ],
    sources: ['Osteoporosis International 2013', 'Thrombosis and Haemostasis'],
  },
  {
    id: 'silica',
    name: 'Silica (Orthosilicic Acid)',
    category: 'bone',
    description: 'Trace mineral for collagen formation and bone health',
    dosage: '5-10mg',
    frequency: 'Daily',
    timing: 'With food',
    effectiveness: 5,
    evidenceLevel: 'weak',
    costPerMonth: { min: 10, max: 25 },
    timelineToResults: '3-6 months',
    riskLevel: 'very_low',
    sideEffects: [],
    interactions: [],
    contraindications: [],
    targetBenefits: ['collagen_formation', 'hair', 'nails', 'bone_health'],
    requiresPrescription: false,
    notes: [
      'Orthosilicic acid is most bioavailable form',
      'May support collagen and connective tissue',
      'Found in beer, oats, some mineral waters',
      'Limited but promising research',
    ],
    sources: ['BMC Musculoskeletal Disorders 2007'],
  },
  {
    id: 'msm',
    name: 'MSM (Methylsulfonylmethane)',
    category: 'bone',
    description: 'Sulfur compound for joint health and collagen',
    dosage: '1000-3000mg',
    frequency: 'Daily',
    timing: 'With food',
    effectiveness: 5,
    evidenceLevel: 'moderate',
    costPerMonth: { min: 10, max: 25 },
    timelineToResults: '4-12 weeks',
    riskLevel: 'very_low',
    sideEffects: ['GI upset', 'Headache (rare)'],
    interactions: [],
    contraindications: [],
    targetBenefits: ['joint_health', 'collagen_support', 'inflammation'],
    requiresPrescription: false,
    notes: [
      'Provides sulfur for collagen and keratin',
      'Often combined with glucosamine for joints',
      'May help with exercise recovery',
      'Generally well-tolerated at high doses',
    ],
    sources: ['Osteoarthritis and Cartilage 2006'],
  },

  // ============================================
  // GENERAL OPTIMIZATION
  // ============================================
  {
    id: 'creatine',
    name: 'Creatine Monohydrate',
    category: 'general',
    description: 'Most studied sports supplement with potential cognitive and skin benefits',
    dosage: '3-5g',
    frequency: 'Daily',
    timing: 'Any time, consistency matters more',
    effectiveness: 9,
    evidenceLevel: 'strong',
    costPerMonth: { min: 5, max: 15 },
    timelineToResults: '4-8 weeks for full saturation',
    riskLevel: 'very_low',
    sideEffects: ['Water retention', 'Weight gain (water/muscle)'],
    interactions: [],
    contraindications: ['Kidney disease'],
    targetBenefits: ['muscle', 'cognitive', 'energy', 'potential_skin_benefits'],
    requiresPrescription: false,
    notes: [
      'Most researched supplement with excellent safety profile',
      'May have anti-aging effects on skin (research emerging)',
      'Monohydrate is the gold standard - no need for fancy forms',
      'Loading phase optional - 3-5g daily works fine',
      'May increase DHT - consider if hair loss is a concern',
    ],
    sources: ['ISSN Position Stand 2017', 'PMC5469049'],
  },
  {
    id: 'magnesium',
    name: 'Magnesium (Glycinate/Threonate)',
    category: 'general',
    description: 'Essential mineral for sleep, stress, and overall health',
    dosage: '200-400mg elemental',
    frequency: 'Daily',
    timing: 'Evening, before bed',
    effectiveness: 8,
    evidenceLevel: 'strong',
    costPerMonth: { min: 10, max: 25 },
    timelineToResults: '2-4 weeks',
    riskLevel: 'very_low',
    sideEffects: ['Loose stools (especially oxide form)'],
    interactions: ['Some antibiotics', 'Bisphosphonates'],
    contraindications: ['Kidney disease'],
    targetBenefits: ['sleep', 'stress_reduction', 'muscle_relaxation', 'heart_health'],
    requiresPrescription: false,
    notes: [
      '50% of population is deficient',
      'Glycinate best for sleep and bioavailability',
      'Threonate may cross blood-brain barrier better',
      'Avoid oxide form - poor absorption, causes diarrhea',
      'Supports 300+ enzymatic reactions',
    ],
    sources: ['NIH Office of Dietary Supplements', 'Nutrients 2017'],
  },
  {
    id: 'glycine',
    name: 'Glycine',
    category: 'general',
    description: 'Amino acid for sleep quality and collagen synthesis',
    dosage: '3g',
    frequency: 'Daily',
    timing: 'Before bed',
    effectiveness: 7,
    evidenceLevel: 'moderate',
    costPerMonth: { min: 10, max: 20 },
    timelineToResults: '1-2 weeks for sleep effects',
    riskLevel: 'very_low',
    sideEffects: ['Mild nausea (rare)'],
    interactions: [],
    contraindications: [],
    targetBenefits: ['sleep_quality', 'collagen_synthesis', 'glycine_synthesis'],
    requiresPrescription: false,
    notes: [
      '3g before bed improves subjective sleep quality',
      'Sweet taste - can be taken in water',
      'Component of collagen (33% of collagen is glycine)',
      'May help with next-day alertness',
    ],
    sources: ['Sleep and Biological Rhythms 2006', 'Neuropsychopharmacology 2015'],
  },
];

// Helper functions
export function getSupplementsByCategory(category: Supplement['category']): Supplement[] {
  return SUPPLEMENTS.filter(s => s.category === category);
}

export function getSupplementsByBenefit(benefit: string): Supplement[] {
  return SUPPLEMENTS.filter(s =>
    s.targetBenefits.some(b => b.toLowerCase().includes(benefit.toLowerCase()))
  );
}

export function getSupplementsByEvidence(minLevel: 'strong' | 'moderate'): Supplement[] {
  const levels = minLevel === 'strong' ? ['strong'] : ['strong', 'moderate'];
  return SUPPLEMENTS.filter(s => levels.includes(s.evidenceLevel));
}

export function getSupplementsByEffectiveness(minEffectiveness: number = 6): Supplement[] {
  return SUPPLEMENTS
    .filter(s => s.effectiveness >= minEffectiveness)
    .sort((a, b) => b.effectiveness - a.effectiveness);
}

export function getOTCSupplements(): Supplement[] {
  return SUPPLEMENTS.filter(s => !s.requiresPrescription);
}

export function getSupplementStack(goals: string[]): Supplement[] {
  const recommendations: Supplement[] = [];
  const seen = new Set<string>();

  for (const goal of goals) {
    const matches = getSupplementsByBenefit(goal);
    for (const match of matches) {
      if (!seen.has(match.id)) {
        seen.add(match.id);
        recommendations.push(match);
      }
    }
  }

  return recommendations.sort((a, b) => b.effectiveness - a.effectiveness);
}
