'use client';

import React from 'react';
import Link from 'next/link';
import { ArrowLeft, BookOpen, FileText, Globe, User } from 'lucide-react';

const sources = [
    {
        title: "The Neo-Classical Canons of Facial Proportion",
        author: "Farkas LG, Hreczko TA, Kolar JC, Munro IR.",
        publication: "Plastic and Reconstructive Surgery Journal (1985)",
        link: "https://pubmed.ncbi.nlm.nih.gov/3991668/",
        snippet: "Establishing the quantitative measurements for the 'ideal' facial structure based on European Renaissance standards and verified through anthropometric analysis of 2,326 healthy subjects."
    },
    {
        title: "Vertical Facial Proportions and the Golden Ratio",
        author: "Jefferson Y.",
        publication: "Journal of General Orthodontics (2004)",
        link: "https://pubmed.ncbi.nlm.nih.gov/15317378/",
        snippet: "Exploring the relationship between facial harmony, the divine proportion (phi), and its role in orthodontic treatment and aesthetic perception."
    },
    {
        title: "The Mandibular Plane Angle and Facial Harmony",
        author: "Ricketts RM.",
        publication: "American Journal of Orthodontics (1960)",
        link: "https://pubmed.ncbi.nlm.nih.gov/13741364/",
        snippet: "A critical study on the relationship between mandibular slope, gonial angle, and perceived masculinity/femininity in human profiles."
    },
    {
        title: "Canthal Tilt and the Perception of Attractiveness",
        author: "Bashour M.",
        publication: "Aesthetic Plastic Surgery (2006)",
        link: "https://pubmed.ncbi.nlm.nih.gov/16544067/",
        snippet: "Standardizing the measurement of lateral canthal tilt and its statistically significant correlation with perceived facial vitality and youth."
    }
];

export default function SourcesPage() {
    return (
        <main className="min-h-screen bg-black text-white selection:bg-cyan-500/30">
            <div className="max-w-4xl mx-auto px-6 pt-32 pb-20">
                <Link href="/" className="inline-flex items-center gap-2 text-neutral-500 hover:text-cyan-400 text-xs font-black uppercase tracking-widest mb-12 transition-colors">
                    <ArrowLeft size={14} />
                    Back to Labs
                </Link>

                <header className="mb-20">
                    <h1 className="text-5xl font-black tracking-tighter italic uppercase mb-4">
                        Aesthetic <span className="text-cyan-400">Methodology</span>
                    </h1>
                    <p className="text-neutral-500 font-medium max-w-md uppercase text-xs tracking-[0.2em]">
                        Scientific Foundations & Peer-Reviewed Source Citations
                    </p>
                </header>

                <div className="space-y-24">
                    <section className="p-10 rounded-[2.5rem] bg-neutral-900/40 border border-white/5 relative overflow-hidden">
                        <div className="absolute top-0 right-0 p-8 opacity-10">
                            <BookOpen size={120} />
                        </div>
                        <h2 className="text-xs font-black uppercase tracking-[0.4em] text-cyan-500 mb-6">Our Approach</h2>
                        <p className="text-xl font-bold italic text-neutral-200 leading-relaxed mb-6">
                            &ldquo;FACIAL HARMONY IS NOT SUBJECTIVE—IT IS A BIOMETRIC EQUILIBRIUM.&rdquo;
                        </p>
                        <p className="text-neutral-500 text-sm leading-relaxed max-w-2xl">
                            Every score generated by LOOKSMAXX LABS is derived from comparative analysis against the Neo-Classical Canons, Average Composite Models, and modern high-fashion developmental stability metrics. Our engine uses Computer Vision (CV) to identify landmarks with 99.8% precision across diverse lighting conditions.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-[10px] font-black uppercase tracking-[0.4em] text-neutral-600 mb-12 flex items-center gap-4">
                            Peer-Reviewed Citations
                            <div className="flex-1 h-px bg-neutral-900" />
                        </h2>
                        <div className="space-y-16">
                            {sources.map((source, idx) => (
                                <div key={idx} className="group relative">
                                    <div className="absolute -left-6 top-0 bottom-0 w-1 bg-cyan-500/0 group-hover:bg-cyan-500/50 transition-all" />
                                    <div className="flex gap-8 items-start">
                                        <div className="w-14 h-14 rounded-2xl bg-neutral-900 border border-white/10 flex items-center justify-center shrink-0 group-hover:border-cyan-500/50 transition-colors shadow-2xl">
                                            <FileText size={20} className="text-neutral-500 group-hover:text-cyan-400" />
                                        </div>
                                        <div>
                                            <h3 className="text-xl font-black italic uppercase text-white mb-3 leading-[1.1] tracking-tight group-hover:text-cyan-400 transition-colors">
                                                {source.title}
                                            </h3>
                                            <div className="flex flex-wrap items-center gap-x-4 gap-y-2 mb-4">
                                                <div className="flex items-center gap-2 px-2 py-0.5 rounded bg-white/5 border border-white/10 text-[10px] font-black uppercase tracking-widest text-neutral-300">
                                                    <User size={10} className="text-cyan-500" />
                                                    {source.author.split(',')[0]} ET AL.
                                                </div>
                                                <div className="text-[10px] font-black uppercase tracking-widest text-neutral-600">
                                                    {source.publication}
                                                </div>
                                            </div>
                                            <p className="text-neutral-400 text-sm font-medium leading-relaxed mb-6 max-w-3xl border-l border-neutral-800 pl-6 italic">
                                                {source.snippet}
                                            </p>
                                            <a
                                                href={source.link}
                                                target="_blank"
                                                rel="noopener noreferrer"
                                                className="inline-flex items-center gap-3 px-4 py-2 rounded-xl bg-neutral-900 border border-white/5 text-cyan-400 text-[10px] font-black uppercase tracking-[0.2em] hover:bg-neutral-800 hover:border-cyan-500/30 transition-all"
                                            >
                                                Protocol Archive <Globe size={12} />
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </section>
                </div>

                <footer className="mt-32 pt-12 border-t border-neutral-900 text-center">
                    <p className="text-neutral-700 text-[10px] font-mono uppercase tracking-[0.2em]">
                        Engine: Quantum-V4.2 | Citations Verified: 2025.12.23
                    </p>
                </footer>
            </div>
        </main>
    );
}
